adam-cli/src/main/scala/org/bdgenomics/adam/cli/CalculateDepth.scala
adam-core/src/main/scala/org/bdgenomics/adam/models/ReferencePosition.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/BroadcastRegionJoin.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/GenomicPartitioners.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/ShuffleRegionJoin.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/BroadcastRegionJoinSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/GenomicPositionPartitionerSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/ShuffleRegionJoinSuite.scala

First pass shuffle-based join impl.  Passes some rudimentary tests.
Certainly needs docs and more tests.
Fixes #528.
Fixes #533.

[ADAM-528][ADAM-533] Adds new RegionJoin impl that is shuffle-based

---

adam-cli/src/test/scala/org/bdgenomics/adam/cli/Features2ADAMSuite.scala

When reading the converted output, it's possible that the order of the records is undefined.  I added a sort which should make things more reliable.
Fixes #532.

[ADAM-532] Fix wigFix intermittent test failure

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/ADAMContextSuite.scala

Let me know if you want me to change anything.  I also updated the
deprecated code and specified a return type for all implicits in
ADAMContext.scala

[ADAM-441] put a check in for Nothing.  Throws an IAE if no return type is provided

---

bin/adam-pyspark
bin/adam-shell
bin/adam-submit
bin/append_to_option.py

Note that this adds a *Python* utility script to `bin/`.  Is this ok?  Parsing the command line in bash just seemed so much less appetizing.  This also has a workaround for SPARK-5185.
Fixes #543.
Fixes #544.

[ADAM-543][ADAM-544] Fix issues with ADAM scripts and classpath

---

adam-cli/src/main/scala/org/bdgenomics/adam/cli/VizReads.scala
adam-cli/src/main/webapp/WEB-INF/layouts/variants.ssp
adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala

Working visualization of variants when given vcf input to ADAM viz
Also added loadGenotypes and maybeLoadVcf in ADAMContext

Variants Visualization

---

adam-cli/src/test/scala/org/bdgenomics/adam/cli/Features2ADAMSuite.scala

Spawned by comments in #557; `Features2ADAMSuite` was using `FunSuite` and `Features2ADAM.run()` was creating a `SparkContext`. This led to address bind errors. This PR changes it so that we pass our own `sc` to `Features2ADAM`, and that this `sc` is created by a `SparkFunSuite`.

Makes Features2ADAMSuite use SparkFunSuite

---

docs/build.sh
docs/source/81_developer_info.md

Resolves #549. Adds a small bit of documentation about how to run and write unit and integration tests for ADAM, as well as documentation about our CI practices.

[ADAM-549] Added documentation for testing and CI for ADAM.

---

adam-cli/src/main/scala/org/bdgenomics/adam/cli/Transform.scala
adam-core/src/main/scala/org/bdgenomics/adam/converters/AlignmentRecordConverter.scala
adam-core/src/main/scala/org/bdgenomics/adam/instrumentation/Timers.scala
adam-core/src/main/scala/org/bdgenomics/adam/models/ReferencePositionPair.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMRDDFunctions.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/ADAMBAMOutputFormat.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/ADAMSAMOutputFormat.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDDFunctions.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/MarkDuplicates.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/correction/TrimReads.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/realignment/IndelRealignmentTarget.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/realignment/RealignIndels.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/realignment/RealignmentTargetFinder.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/recalibration/Recalibrator.scala

This moves the Timers object back from bdg-utils to ADAM, as it contains ADAM-specific timers. 
I'll raise another PR to remove the Timers object from bdg-utils, but I don't think it's necessary to make a new bdg-utils release or anything.

Moved the Timers object from bdg-utils back to ADAM

---

adam-core/src/main/scala/org/bdgenomics/adam/instrumentation/Timers.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/recalibration/Covariate.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/recalibration/ObservationTable.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/recalibration/Recalibrator.scala
adam-core/src/main/scala/org/bdgenomics/adam/util/QualityScore.scala
adam-core/src/main/scala/org/bdgenomics/adam/util/Util.scala

Some notes:
* When looking at the performance of BQSR the `Util.hashCombine` method appeared to perform poorly, so I have replaced its usage in `CovariateKey` and `QualityScore` with hash codes based on the recipe from Programming in Scala (http://www.artima.com/pins1ed/object-equality.html). 
* On my small test data set of about 90,000 reads this change makes `ObservationAccumulator.+=` about 3.5 times faster, making BQSR about 50% faster in total (not including times for loading, saving files etc). I'm aware that this is not a particularly realistic test, but I think it's probably sufficient for such a low-risk change.
* I have also removed `Util.hashCombine` method and replaced its other usages, since others may use it without being aware of the performance penalty.
* This change also …

Changed hashCode implementations to improve performance of BQSR

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMRDDFunctions.scala

Resolves #563. Prints warning if file does not have "*.adam" extension.

[ADAM-563] Add warning message when saving Parquet files with incorrect extension

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/correction/TrimReads.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/correction/TrimReadsSuite.scala

Resolves #578. Adds logic to track the end of the read when trimming. Evidently, this wasn't in there. I think this code may have been in the repository before we added the `end` field back, and we forgot to tack the `end` logic back on.

[ADAM-578] Update end of read when trimming.

---

adam-core/src/main/scala/org/bdgenomics/adam/converters/SAMRecordConverter.scala
adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala

Resolves #479. Also adds a bit of logging to the legacy format converters.

A few small conversion fixes

---

adam-core/src/main/scala/org/bdgenomics/adam/converters/FragmentConverter.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/contig/NucleotideContigFragmentRDDFunctions.scala
adam-core/src/test/scala/org/bdgenomics/adam/converters/FragmentConverterSuite.scala

Resolves #571. Adds support for loadings FASTA files and `*.contig.adam` files in as `AlignmentRecords`. Depends on #567.

Add support for converting contigs into reads

---

adam-cli/src/main/scala/org/bdgenomics/adam/cli/ADAMMain.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/CountContigKmers.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/ReferencePartitioner.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/contig/FlankReferenceFragments.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/contig/NucleotideContigFragmentRDDFunctions.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/contig/FlankReferenceFragmentsSuite.scala

Resolves #583. This steals some code from https://github.com/bigdatagenomics/avocado/pull/127 that adds flanking sequence to adjacent fragments. Without adding the adjacent sequence, we won't get correct values.

[ADAM-583] Add k-mer counting functionality for nucleotide contig fragments

---

adam-core/src/main/scala/org/bdgenomics/adam/converters/AlignmentRecordConverter.scala
adam-core/src/test/scala/org/bdgenomics/adam/converters/AlignmentRecordConverterSuite.scala

Resolves #452. Small change that stops setting SM attribute to recordGroupSample in ADAM to BAM conversion.

[ADAM-452] Fixes SM attribute on ADAM to BAM conversion.

---

adam-cli/src/main/scala/org/bdgenomics/adam/cli/ADAM2Vcf.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/AlleleCount.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/Fasta2ADAM.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/PluginExecutor.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/Vcf2ADAM.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/VcfAnnotation2ADAM.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala
adam-core/src/test/scala/org/bdgenomics/adam/predicates/GenotypePredicatesSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDDFunctionsSuite.scala

I think this resolves what we were discussing on #587 last night. CC @laserson @ryan-williams for thoughts and review.

[ADAM-587] Clean up loading checks.

---

adam-cli/src/main/scala/org/bdgenomics/adam/cli/ADAMMain.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/CountContigKmers.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/CountReadKmers.scala

Resolves #612. I also renamed `CountKmers` to `CountReadKmers` for clarity.

[ADAM-612] Point to proper k-mer counters.

---

adam-apis/src/main/scala/org/bdgenomics/adam/apis/java/JavaADAMContext.scala
adam-apis/src/test/scala/org/bdgenomics/adam/apis/java/JavaADAMContextSuite.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/VcfAnnotation2ADAM.scala
adam-core/pom.xml
adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala
adam-core/src/test/scala/org/bdgenomics/adam/algorithms/consensus/ConsensusGeneratorFromReadsSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/predicates/GenotypePredicatesSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/ADAMContextSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/realignment/IndelRealignmentTargetSuite.scala
pom.xml

See discussion on https://github.com/bigdatagenomics/adam/issues/565

[ADAM-565] Upgrade to Parquet filter2 API.

---

adam-cli/src/main/scala/org/bdgenomics/adam/cli/CalculateDepth.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/BroadcastRegionJoin.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/RegionJoin.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/ShuffleRegionJoin.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/BroadcastRegionJoinSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/ShuffleRegionJoinSuite.scala

Resolves #600. @tdanford @laserson thoughts about this?

[ADAM-600] Adding RegionJoin trait.

---

adam-cli/src/main/scala/org/bdgenomics/adam/cli/Transform.scala
adam-core/src/main/scala/org/bdgenomics/adam/models/RecordGroupDictionary.scala
adam-core/src/main/scala/org/bdgenomics/adam/models/SequenceDictionary.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala

Resolves #625. Elaborates the glob before loading the header.

[ADAM-625] Enable globbing for BAM.

---

adam-core/pom.xml
pom.xml

Resolves #540. Moves to the new HTSJDK release which removes the Cofoja dependency that was blocking Java 8 support. A few notes:
* I have not tested this on Java 8 as I don't have a system with Java 8 on it; @antonkulaga would you mind trying to build this?
* I want to test this a bit further. It requires some funny shading in Hadoop-BAM; I'm _optimistic_ that we don't need to do anything more than the funny shading, but I realize that optimism is likely wrong.

[ADAM-540] Move to new HTSJDK release; should support Java 8.

---

.gitignore
adam-cli/src/main/scala/org/bdgenomics/adam/cli/CalculateDepth.scala
adam-core/src/main/scala/org/bdgenomics/adam/models/ReferencePosition.scala
adam-core/src/main/scala/org/bdgenomics/adam/models/ReferencePositionPair.scala
adam-core/src/main/scala/org/bdgenomics/adam/models/ReferenceRegion.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/ShuffleRegionJoin.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/contig/NucleotideContigFragmentRDDFunctions.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDDFunctions.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/MarkDuplicates.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/realignment/IndelRealignmentTarget.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/realignment/RealignIndels.scala
adam-core/src/main/scala/org/bdgenomics/adam/rich/RichAlignmentRecord.scala
adam-core/src/main/scala/org/bdgenomics/adam/serialization/ADAMKryoRegistrator.scala
adam-core/src/test/scala/org/bdgenomics/adam/models/ReferencePositionSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/models/ReferenceRegionSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/BroadcastRegionJoinSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/ShuffleRegionJoinSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDDFunctionsSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/MarkDuplicatesSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/recalibration/BaseQualityRecalibrationSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rich/RichAlignmentRecordSuite.scala

Resolves #574, depends on #623. In this pull request, we associate unmapped reads with a reference position that is derived from either their read name or their read sequence during the sort and duplicate marking phases. Specifically, sort uses `ZZZ<read_name>` and duplicate marking uses `<read_sequence>` as the contig name. Unmapped reads are placed at position 0 on the contig. Conceptually, this change should also enable duplicate marking on unmapped reads. I haven't tested this yet, but will spin a cluster up sometime soon.

Conceptual fix for duplicate marking and sorting stragglers

---

adam-cli/src/main/scala/org/bdgenomics/adam/cli/ADAM2Vcf.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variation/VariationRDDFunctions.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/variation/VariationRDDFunctionsSuite.scala

Resolves #631. Renames `adamVCFSave` to `saveAsVcf` and adds hooks to optionally coalesce and sort during save. Sort is performed _after_ coalescing. Sort and coalesce are independent.

[ADAM-631] Allow VCF conversion to sort on output after coalescing.

---

adam-core/src/main/scala/org/bdgenomics/adam/algorithms/smithwaterman/SmithWaterman.scala
adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantAnnotationConverter.scala
adam-core/src/main/scala/org/bdgenomics/adam/rich/RichAlignmentRecord.scala
adam-core/src/test/scala/org/bdgenomics/adam/util/MdTagSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/util/NormalizationUtilsSuite.scala
pom.xml

[ADAM-640] Fix incorrect exclusion for org.seqdoop.htsjdk.

---

adam-cli/src/test/scala/org/bdgenomics/adam/cli/Features2ADAMSuite.scala
adam-cli/src/test/scala/org/bdgenomics/adam/cli/FlattenSuite.scala
adam-cli/src/test/scala/org/bdgenomics/adam/cli/ParquetLister.scala

This is a part of https://github.com/bigdatagenomics/adam/issues/634 to remove unused Parquet-specific code.

[ADAM-634] Create a local ParquetLister for testing purposes.

---

adam-core/src/main/scala/org/bdgenomics/adam/converters/AlignmentRecordConverter.scala
adam-core/src/main/scala/org/bdgenomics/adam/converters/SAMRecordConverter.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/recalibration/BaseQualityRecalibration.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/recalibration/Recalibrator.scala
adam-core/src/main/scala/org/bdgenomics/adam/rich/DecadentRead.scala
adam-core/src/test/scala/org/bdgenomics/adam/converters/AlignmentRecordConverterSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/converters/SAMRecordConverterSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rich/DecadentReadSuite.scala

Resolves #646. Allows the creation of `DecadentRead`s with `*` quality scores. These reads are then not observed or corrected during BQSR.

[ADAM-646] Special case reads with '*' quality during BQSR.

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/GenomicPartitioners.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/GenomicPositionPartitionerSuite.scala

Resolves #666. Checks sequence dictionary when partitioning keys and throws an `IllegalArgumentException` with the violating key and a list of known contigs.

[ADAM-666] Clean up key not found error in partitioner code.

---

adam-core/src/main/scala/org/bdgenomics/adam/models/Gene.scala
adam-core/src/test/scala/org/bdgenomics/adam/models/ReferenceUtilsSuite.scala

- fixed pattern matching bug in `ReferenceUtils.unionReferenceSet`
- added test suite `ReferenceUtilsSuite`

Bug fix in ReferenceUtils.unionReferenceSet

---

adam-cli/src/main/scala/org/bdgenomics/adam/cli/PluginExecutor.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/BroadcastRegionJoin.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/ShuffleRegionJoin.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/ADAMContextSuite.scala
scripts/scala-console.scala

make adamLoad public

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/features/FeatureParser.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDDFunctions.scala
adam-core/src/main/scala/org/bdgenomics/adam/rich/RichAlignmentRecord.scala

fix BAM/SAM header setting when writing on cluster

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/features/FeatureRDDFunctions.scala

GeneFeatureRDDFunctions → FeatureRDDFunctions

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/ShuffleRegionJoin.scala

removing in #684 was a mistake, assumed it was redundant but it's not!

restore clause guarding pruneCache check

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/ShuffleRegionJoin.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/ShuffleRegionJoinSuite.scala

class-ify ShuffleRegionJoin, force setting seqdict

---

adam-core/src/main/scala/org/bdgenomics/adam/models/ReferenceRegion.scala
adam-core/src/main/scala/org/bdgenomics/adam/models/SequenceDictionary.scala

include SequenceRecords from second-in-pair reads

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala

Resolves #718. Uses @jfeala's proposed fix. @jfeala, let me know if you'd like credit on the commit and I'll modify the commit author.

[ADAM-718] Use filesystem path to get underlying file system.

---

adam-core/src/main/scala/org/bdgenomics/adam/converters/AlignmentRecordConverter.scala
adam-core/src/main/scala/org/bdgenomics/adam/converters/SAMRecordConverter.scala

Resolves #729. Ensures that TLEN is pushed back into the correct place in SAM on conversion back.

[ADAM-729] Stuff TLEN into attributes.

---

adam-core/src/main/scala/org/bdgenomics/adam/util/AttributeUtils.scala

Expanded definition of attribute strings to allow for attribute names of up to four characters.

Fixed bug preventing use of TLEN attribute

---

pom.xml

[ADAM-743] exclude conflicting jackson dependencies

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMRDDFunctions.scala
pom.xml

This fixes an issue that appears when using `and`ed predicates to drop blocks on statistics; specifically, there is a bug pre-1.8.0 where fewer blocks are dropped than should be, which leads to bad performance.

Upgrade to Parquet 1.8.1.

---

adam-core/src/main/scala/org/bdgenomics/adam/rich/RichAlignmentRecord.scala
adam-core/src/main/scala/org/bdgenomics/adam/util/MdTag.scala
adam-core/src/test/scala/org/bdgenomics/adam/util/MdTagSuite.scala

Sorry all, looks the code in #727 contains a few errors when it came to parsing mismatches mixed with insertions.  I added a quite a few tests to cover this case and other complex mdtags.
If you think there are interesting cases not covered in the new tests now let me know!
Thanks!

Fix for mdtag issues with insertions

---

bin/adam-submit
bin/compute-adam-jars.sh

The `./bin/compute-adam-jars.sh` script does not remote the `adam-cli` JAR from the classpath. This exposes [SPARK-1921](https://issues.apache.org/jira/browse/SPARK-1921) when running on YARN.

Remove adam-cli jar from classpath during adam-submit

---

adam-core/src/main/scala/org/bdgenomics/adam/algorithms/consensus/ConsensusGeneratorFromKnowns.scala
adam-core/src/main/scala/org/bdgenomics/adam/models/Consensus.scala

Resolves #769. There was a `SparkContext` in the known indel consensus model that was not annotated with transient, which caused the serialization issues.

[ADAM-769] Fix serialization issue in known indel consensus model.

---

bin/adam-shell
bin/adam-submit

Since we removed `ADAM_OPTS` in #754, we should warn the user if they have ADAM_OPTS set and aren't passing any Spark options otherwise.

We should print a warning message if the user has ADAM_OPTS set.

---

adam-core/pom.xml
adam-core/src/test/scala/org/bdgenomics/adam/util/ADAMFunSuite.scala
pom.xml
scripts/jenkins-test

Resolves build comments on #752. I have set Jenkins up as a 3D!!!!!! matrix:

[ADAM-752] Build for many combos of Spark/Hadoop versions.

---

adam-core/src/main/scala/org/bdgenomics/adam/util/AttributeUtils.scala
adam-core/src/test/scala/org/bdgenomics/adam/util/AttributeUtilsSuite.scala

Page 6 of the SAMv1 specs allow for numeric array tags (TYPE="B"), with values matching:
```
[cCsSiIf](,[-+]?[0-9]*\.?[0-9]+([eE][-+]?[0-9]+)?)+
```
This update of `org.bdgenomics.adam.util.AttributeUtils.typedStringToValue` skips the first character (a numeric type specifier) plus the leading comma, before trying to convert to a numeric array. This bug was breaking `loadAlignments` for BAM files generated by the STAR RNA-Seq aligner, which creates type "B" tags by default.

Fix SAM Attribute parser for numeric array tags

---

adam-cli/src/main/scala/org/bdgenomics/adam/cli/Transform.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDDFunctions.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/recalibration/BaseQualityRecalibration.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/recalibration/Recalibrator.scala
adam-core/src/main/scala/org/bdgenomics/adam/rich/DecadentRead.scala
adam-core/src/test/scala/org/bdgenomics/adam/rich/DecadentReadSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/util/MdTagSuite.scala

[ADAM-777] Add validation stringency flag for BQSR.

---

adam-cli/src/main/scala/org/bdgenomics/adam/cli/Fasta2ADAM.scala

Resolves #791. This allows someone who is converting a FASTA file into ADAM to set the number of output partitions they would like.

[ADAM-791] Add repartition parameter to Fasta2ADAM.

---

adam-cli/src/main/scala/org/bdgenomics/adam/cli/Transform.scala
adam-core/src/main/scala/org/bdgenomics/adam/models/SequenceDictionary.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDDFunctions.scala
adam-core/src/test/resources/sorted.sam
adam-core/src/test/scala/org/bdgenomics/adam/models/SequenceDictionarySuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDDFunctionsSuite.scala

This change resolves #783 and #760. Specifically, now we write the SAM/BAM @SQ header
lines using the same lexicographic ordering that we use for sorting records, and we write the @HD line to note that we are sorted in coordinate order.

[ADAM-783] Write @SQ header lines in sorted order.

---

adam-core/src/main/scala/org/bdgenomics/adam/models/SequenceDictionary.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDDFunctions.scala
adam-core/src/test/resources/unsorted.sam
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDDFunctionsSuite.scala

fix unmapped-read sorting

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala

Better transform error when file doesn't exist

---

adam-core/src/main/scala/org/bdgenomics/adam/models/ReferenceRegion.scala

fix `Long != null` warnings

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDDFunctions.scala

- `logError` for `LENIENT`
- `throw` for `STRICT

better validation when saving paired fastqs

---

adam-cli/src/main/scala/org/bdgenomics/adam/cli/FlagStat.scala

Lesson: don't pick [random encodings from `DataOutputStream`](http://docs.oracle.com/javase/7/docs/api/java/io/DataOutputStream.html?is-external=true#writeUTF(java.lang.String)) to output your files in!
Also, cleans up some extra whitespace.

fix flagstat output file encoding

---

adam-core/src/main/scala/org/bdgenomics/adam/util/ParquetLogger.scala

Fixed the ParquetLogger utility so that it silences `org.apache.parquet.hadoop`
instead of `parquet.hadoop`. All is quiet again. Resolves #851.

[ADAM-851] Slienced Parquet logging.

---

adam-core/src/main/scala/org/bdgenomics/adam/rich/DecadentRead.scala

This change changes the DecadentRead class and object from public to package
private (org.bdgenomics.adam). Additionally, we mark both items as deprecated
in favor of the RichAlignmentRecord. Resolves #780.

[ADAM-780] Make DecadentRead package private.

---

bin/adam-shell
bin/adam-submit

Because of `set -e`, the `which spark-submit` subshell command was causing the script to exit early.
Fixes #857.

[ADAM-857] Corrected handling of env vars in bin scripts

---

scripts/changelog.sh
scripts/commit-pr.sh
scripts/release/release.sh

These two commits contain two changes:
1. The first commit modifies the release scripts to move to a branch-then-release model.
2. The second commit adds a script `script/commit-pr.sh` that automates the process of FF merging a PR from the command line.
Recently, someone (@ryan-williams?) mentioned the idea of moving to a branch-then-release model. Here, we would make a branch, and then make the release off of this branch. The release commits would not show up on the master branch. This would make it easier to make maintenance releases. Although the Maven release plugin contains a goal for releasing from a branch, the general consensus is that this goal works with SVN but not with Git (I tested this out and this does seem to be the case). It seems like many people advocate the "Gitflow" …

New release and pr-commit scripts

---

adam-cli/src/main/scala/org/bdgenomics/adam/cli/ADAM2Fasta.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/Transform.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/Vcf2ADAM.scala

Resolves #864. In Spark, coalescing will reduce the number of partitions in an
RDD without performing a shuffle, but coalescing will only increase the number
of partitions if a shuffle is performed. This PR modifies Transform and Vcf2ADAM
to check whether the coalesce option will increase or decrease the partition
count. Additionally, it adds a flag that allows the user to force a shuffle;
this may be desirable as this causes a HashPartitioned shuffle, which may
improve the balance of records across partitions.

[ADAM-864] Don't force shuffle if reducing partition count.

---

scripts/commit-pr.sh

@heuermh this should fix the issue you were seeing.

Minor fix to commit script to support https.

---

adam-cli/src/main/scala/org/bdgenomics/adam/cli/Transform.scala

The Transform pipeline in the CLI has several stages (e.g., sort, indel
realignment, BQSR) that trigger recomputation. If you are running a single
stage off of local storage/HDFS/Tachyon, this is OK. However, if you're running
multiple stages, or you are loading data from S3/etc, this can lead to serious
performance degradation. To address this, I've added the proper caching
statements. Additionally, I've added a hook so that the user can specify the
storage level to use for caching. Resolves #883.

[ADAM-883] Add caching to Transform pipeline.

---

adam-core/src/main/scala/org/bdgenomics/adam/rich/RichGenotype.scala

I added the is* genotype methods from HTS-JDK Genotype to Adam RichGenotype. 
This makes it easier to filter on a genotypeRDD.
Compare for instance 
`genotypeRDD.filter(_.isHom)`
to
`genotypeRDD.filter(gt => (gt.getType = GenotypeType.HOM_REF) || (gt.getType = GenotypeType.HOM_ALT)  )` 
These methods are copied almost exactly from from
https://github.com/samtools/htsjdk/blob/master/src/java/htsjdk/variant/variantcontext/Genotype.java#L230
I did not add `isMixed` and `isAvailable` since Adam seems to handle these Genotypes the same as GenotypeType.NO_CALL

Added is* genotype methods from HTS-JDK Genotype to RichGenotype

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala

Closes #891. In org.bdgenomics.adam.rdd.ADAMContext, the val sparkContext:
SparkContext is not marked as @transient, which causes serialization issues.
SparkContexts are not serializable and should only be called from the driver.

[ADAM-891] Mark SparkContext as @transient.

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/ADAMBAMOutputFormat.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/ADAMSAMOutputFormat.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDDFunctions.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDDFunctionsSuite.scala

This is a rebase of the code contributed by @antonstamov as PR #733, but rebased onto the latest changes, and with unit tests added for the single file save code.

Single file save from #733, rebased

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/GenomicPartitioners.scala

[ADAM-914] Create a GenomicRegionPartitioner given a partition count.

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/ADAMBAMOutputFormat.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/ADAMSAMOutputFormat.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDDFunctions.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDDFunctionsSuite.scala

Resolves #916. Not fully done yet; seems to work for BAM but not SAM. The SAM file header doesn't write correctly... Still debugging that. Needs more testing.

[ADAM-916] New strategy for writing header.

---

README.md

Looks something like [this](https://github.com/bigdatagenomics/adam/files/89677/Untitled.Document.md.pdf)...

Change the README to use adam-shell -i instead of pasting

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/contig/NucleotideContigFragmentRDDFunctions.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/contig/NucleotideContigFragmentRDDFunctionsSuite.scala

adamGetReferenceString reduces pairs correctly, fixes #967

---

adam-cli/src/main/scala/org/bdgenomics/adam/cli/FlagStat.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala

add validation stringency to bam parsing, flagstat

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDDFunctions.scala
adam-core/src/test/scala/org/bdgenomics/adam/projections/FieldEnumerationSuite.scala

Fixes #945 
This results in a Parquet folder structure of
```
$ ls -ls /var/folders/3y/61r1w_cs4hbdr_34nrdrbhww0000gn/T/3911097172870281306/reads12.adam
total 176
8 -rw-r--r--   1 user  staff      8 Mar 24 17:38 ._SUCCESS.crc
8 -rw-r--r--   1 user  staff     92 Mar 24 17:38 ._common_metadata.crc
8 -rw-r--r--   1 user  staff    120 Mar 24 17:38 ._metadata.crc
8 -rw-r--r--   1 user  staff     20 Mar 24 17:38 ._rgdict.avro.crc
8 -rw-r--r--   1 user  staff     20 Mar 24 17:38 ._seqdict.avro.crc
8 -rw-r--r--   1 user  staff    204 Mar 24 17:38 .part-r-00000.gz.parquet.crc
0 -rw-r--r--   1 user  staff      0 Mar 24 17:38 _SUCCESS
24 -rw-r--r--   1 user  staff  10494 Mar 24 17:38 _common_metadata
32 -rw-r--r--   1 user  staff  14304 Mar 24 17:38 _metadata
8 -rw-r--r--   1 user  staff   1247 Mar …
```

Use .adam/_{seq,rg}dict.avro paths for Avro-formatted dictionaries

---

scripts/jenkins-test

Add -print_metrics option to Jenkins build

---

pom.xml

Fixes #1029 
Modifies pom.xml version properties so should be merged before bdg-formats is bumped to 0.8.0.

Increase Avro dependency version to 1.8.0

---

adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala
adam-core/src/test/scala/org/bdgenomics/adam/converters/VariantContextConverterSuite.scala

I added info fields only if the vcf is from a single sample.
What's the desired behavior if the vcf has multiple samples per site?

adam2vcf doesn't have info fields

---

scripts/jenkins-test

Resolves #1008. As per discussion with @shaneknapp, it is preferable to support builds across Java versions by manually setting JAVA_HOME in a shell script run inside of Jenkins. This is due to certain configuration limitations inside of Jenkins. Currently, we are doing this via a script tracked inside of Jenkins. I would rather roll all of that config into the ./scripts/jenkins-test script so that we have revision control, etc.

[ADAM-1008] Modify jenkins-test script to support Java 8 build.

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDD.scala

It seems like we were doing something incorrectly when writing the header. Additionally, we now write a correct end-of-file. Resolves #962.

[ADAM-962] Fix corrupt single-file BAM output.

---

adam-core/src/main/scala/org/bdgenomics/adam/converters/AlignmentRecordConverter.scala
adam-core/src/main/scala/org/bdgenomics/adam/converters/SAMRecordConverter.scala
adam-core/src/main/scala/org/bdgenomics/adam/util/AttributeUtils.scala
adam-core/src/test/scala/org/bdgenomics/adam/converters/SAMRecordConverterSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/util/AttributeUtilsSuite.scala

[ADAM-1061] Clean up attributes regex and denormalized fields

---

adam-cli/src/main/scala/org/bdgenomics/adam/cli/Transform.scala

Resolves #1053. Split out into many commits for reviewer convenience, but also to make it easier to address merge conflicts when #1011 merges. Will squash before merge.

[ADAM-1053] Clean up Transform

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/variation/GenotypeRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variation/VariantContextRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/serialization/ADAMKryoRegistrator.scala

Resolves #1100. Registered `Sample` class with the `AvroSerializer` in `ADAMKryoRegistrator`.
I've tested this locally. @jpdna can you verify this works on your side as well?

[ADAM-1100] Resolve Sample Not Serializable exception

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMRDDFunctions.scala
adam-core/src/main/scala/org/bdgenomics/adam/util/ParquetFileTraversable.scala

FileSystem.get returns the configured default file system. This can cause issues when loading a file off a non-default FileSystem, e.g., an NFS or S3. This PR changes to use Path.getFileSystem. Resolves #1087.

[ADAM-1087] Migrate away from FileSystem.get

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/realignment/IndelRealignmentTarget.scala
adam-core/src/main/scala/org/bdgenomics/adam/serialization/ADAMKryoRegistrator.scala

Resolves #1136. Rewrote IndelRealignmentTarget/ZippedTargetSet serializers to resolve potential StackOverflowException.
Also, fixed one `FileSystem.get` that I'd missed in 4140095736332d6ae94418595c3911b8ffa171dd.

[ADAM-1136] Transform runs successfully with kryo registration required

---

adam-core/src/main/scala/org/bdgenomics/adam/serialization/ADAMKryoRegistrator.scala

Reorder kryo.register statements in ADAMKryoRegistrator

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/GenomicPartitioners.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/GenomicPositionPartitionerSuite.scala

GenomicRegionPartitioner and GenomicPositionPartitioner can now accept an extra key. This can be used for keyBy() on cell type, sampleId, etc.

Updated GenomicPartitioners to accept additional key.

---

adam-apis/src/test/java/org/bdgenomics/adam/apis/java/JavaADAMFeatureConduit.java
adam-cli/src/main/scala/org/bdgenomics/adam/cli/ADAM2Vcf.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/ADAMMain.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/Reads2Coverage.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/TransformFeatures.scala
adam-cli/src/test/scala/org/bdgenomics/adam/cli/TransformFeaturesSuite.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/FileMerger.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/SAMHeaderWriter.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/features/CoverageRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/features/FeatureParser.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/features/FeatureRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/features/Features.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/ADAMBAMOutputFormat.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/ADAMSAMOutputFormat.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variation/ADAMVCFOutputFormat.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variation/VariantContextRDD.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/features/CoverageRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/features/FeatureRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/variation/VariantContextRDDSuite.scala

Resolves #1009, #1059, #1058, #676.

Resolves various single file save/header issues

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/variation/VariantContextRDD.scala
pom.xml
scripts/jenkins-test
scripts/move_to_spark_2.sh
scripts/release/release.sh

Relies on https://github.com/bigdatagenomics/utils/pull/78. Resolves #1093:
* Clean up logging in VariantContextRDD
* Add move_to_spark_2.sh script and CI hooks

[ADAM-1093] Move to support Spark 2.0.0.

---

adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDDSuite.scala
pom.xml

Fixes #1158 
Currently fails one unit test
```bash
$ mvn test
...
- write single bam file back *** FAILED ***
htsjdk.samtools.SAMFormatException: Does not seem like a BAM file
at org.seqdoop.hadoop_bam.BAMSplitGuesser.<init>(BAMSplitGuesser.java:88)
at org.seqdoop.hadoop_bam.BAMInputFormat.addProbabilisticSplits(BAMInputFormat.java:234)
at org.seqdoop.hadoop_bam.BAMInputFormat.getSplits(BAMInputFormat.java:161)
at org.seqdoop.hadoop_bam.AnySAMInputFormat.getSplits(AnySAMInputFormat.java:252)
at org.apache.spark.rdd.NewHadoopRDD.getPartitions(NewHadoopRDD.scala:120)
```

Update Hadoop-BAM to version 7.7.0

---

adam-cli/src/main/scala/org/bdgenomics/adam/cli/ADAMMain.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/Fragments2Reads.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/MergeShards.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/Reads2Fragments.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/Transform.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/View.scala
adam-cli/src/test/resources/artificial.fa
adam-cli/src/test/resources/artificial.fa.fai
adam-cli/src/test/scala/org/bdgenomics/adam/cli/MergeShardsSuite.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMRDDFunctions.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/FileMerger.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/GenomicRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/features/FeatureRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variation/VariantContextRDD.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/ADAMContextSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/FileMergerSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/util/ADAMFunSuite.scala

Refactor CLIs for merging sharded files

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala

[ADAM-1179] Improve error message when globbing a parquet file fails.

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/ADAMContextSuite.scala

Resolves #1186. Check for a null pointer in ADAMContext.getFiles. Make ADAMContext.getFsAndFiles package private so that we can unit test it. Added unit tests to check for proper exception with empty directories and bad globs.

[ADAM-1186] Mask null from fs.globStatus.

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/BroadcastRegionJoin.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/GenomeBins.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/GenomicRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/RegionJoin.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/ShuffleRegionJoin.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/InnerBroadcastRegionJoinSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/InnerShuffleRegionJoinSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/LeftOuterShuffleRegionJoinSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/OuterRegionJoinSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/RightOuterBroadcastRegionJoinSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/RightOuterShuffleRegionJoinSuite.scala

Resolves #1098. Still a WIP; needs tests, as well as more documentation.

Add outer joins

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/realignment/IndelRealignmentTarget.scala

Updates `org.bdgenomics.adam.rdd.read.realignment.TargetSetSerializer` to manually (de)serialize each set element, instead of delegating to Kryo. This eliminates a stack overflow from inside of Kryo. Resolves #1190.
I have tested this on the cluster.

[ADAM-1190] Manually (un)pack IndelRealignmentTarget set.

---

scripts/release/release.sh

Fixes #1211 
Since the `move_to_scala_2.11.sh` script needs to be reapplied after `git checkout`, I reordered the Scala 2.10 and 2.11 sections for Spark 2.x releases.

[ADAM-1211] Fix call to move_to_scala_2.sh, reorder Spark 2.x Scala 2.10 and 2.10 sections

---

adam-assembly/src/main/scala/org/bdgenomics/adam/assembly/Assembly.scala
bin/adam-shell
bin/adam-submit

[ADAM-1212] Add empty assembly object, allows Maven build to create sources and javadoc artifacts

---

pom.xml
scripts/move_to_spark_2.sh

Reverts #1254, then reapplies commit but while fixing sed replacement line.

[ADAM-1221] Bump Spark/Hadoop versions.

---

adam-core/src/test/scala/org/bdgenomics/adam/util/ADAMFunSuite.scala
pom.xml

Resolves #1225. Depends on https://github.com/bigdatagenomics/utils/pull/89 and a bdg-utils 0.2.9 release.

[ADAM-1225] Move helper functions from ADAMFunSuite to SparkFunSuite.

---

adam-core/src/test/resources/fastq_to_usam.py

`FragmentRDDSuite` fails on my laptop, where the first `python` on the path is apparently `python3`

make py file py3-forward-compatible

---

adam-core/src/main/scala/org/bdgenomics/adam/converters/SupportedHeaderLines.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/GenomicRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/VCFHeaderUtils.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/GenotypeRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/VariantAnnotationRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/VariantContextRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/VariantRDD.scala
adam-core/src/test/resources/sorted.lex.vcf
adam-core/src/test/resources/sorted.vcf
adam-core/src/test/scala/org/bdgenomics/adam/rdd/ADAMContextSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/variant/VariantContextRDDSuite.scala

Resolves #1233. Adds a `headerLines` field to all Variant-related GenomicRDDs. In the current implementation, this field is populated by the set of all header lines for all INFO/FORMAT fields that we support. In a future patch, we will also store the header lines that correspond to fields that do not map to a specific field in the Variant/Genotype schema, and that are stored in an
attribute map.

[ADAM-1233] Expose header lines in Variant-related GenomicRDDs

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/GenomicRDD.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDDSuite.scala

for multiple regions data select.

add function:filterByOverlappingRegions

---

adam-core/src/test/scala/org/bdgenomics/adam/util/ADAMFunSuite.scala

Resolves #1280.
I tried for a while but couldn't silence the Parquet logging in the tests. We're still on Parquet 1.8.1, which messes with the Java util logging package, while Parquet 1.9.0 upgrades to Log4j. I figured that we'll punt on silencing the Parquet logs until we upgrade to 1.9.0, since that should then be a trivial fix.

[ADAM-1280] Silence CRAM logging in tests.

---

docs/source/40_deploying_ADAM.md
docs/source/bibliography.bib

[ADAM-493] Add ADAM-on-Spark-on-YARN docs.

---

docs/source/60_building_apps.md

Add docs about building downstream applications

---

adam-apis/src/main/scala/org/bdgenomics/adam/apis/java/JavaADAMContext.scala
adam-apis/src/test/scala/org/bdgenomics/adam/apis/java/JavaADAMContextSuite.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/ADAMContextSuite.scala

Fixes #1296 
This came up again when I was making code style fixes to adam-apis (e.g. https://github.com/bigdatagenomics/adam/blob/master/adam-apis/src/test/java/org/bdgenomics/adam/apis/java/JavaADAMAnnotationConduit.java#L44).

Make ADAMContext and JavaADAMContext constructors public

---

docs/source/60_building_apps.md

Follow on from @heuermh's #1304.

Add docs about using ADAM's Kryo registrator from another Kryo registrator.

---

adam-core/src/main/scala/org/bdgenomics/adam/converters/FragmentConverter.scala
adam-core/src/main/scala/org/bdgenomics/adam/models/ReferencePosition.scala
adam-core/src/main/scala/org/bdgenomics/adam/models/ReferenceRegion.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/FeatureRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/MDTagging.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/realignment/IndelRealignmentTarget.scala
adam-core/src/test/scala/org/bdgenomics/adam/models/NonoverlappingRegionsSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/models/ReferenceRegionSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/InnerShuffleRegionJoinSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/InnerTreeRegionJoinSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/OuterRegionJoinSuite.scala

Resolves #1285 and #1286. The first two commits need to be squashed together.

Reference region cleanup

---

README.md

Why Adam? section added to README.md

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/ShuffleRegionJoin.scala

Resolves #1308. CC @akmorrow13 @devin-petersohn

[ADAM-1308] Fix stack overflow in join with custom iterator impl.

---

pom.xml

[ADAM-1322] Skip git commit plugin if .git is missing.

---

scripts/jenkins-test
scripts/move_to_scala_2.10.sh
scripts/move_to_scala_2.11.sh
scripts/move_to_spark_1.sh
scripts/move_to_spark_2.sh

Resolves #1317. Depends on #1318.
CC @shaneknapp this should prevent the problem you saw this week from happening again.

Add interlocks for move_to_xyz scripts.

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/VCFHeaderUtils.scala

Resolves #1337. The VCF writer calls close on the underlying stream.

[ADAM-1337] Remove os.{flush,close} calls after writing VCF header.

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala

[ADAM-1339] Use glob-safe method to load VCF header metadata for Parquet

---

adam-core/src/main/scala/org/bdgenomics/adam/models/ReferenceRegion.scala
adam-core/src/main/scala/org/bdgenomics/adam/models/VariantContext.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/GenomicRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/TreeRegionJoin.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/contig/NucleotideContigFragmentRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/CoverageRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/FeatureRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/fragment/FragmentRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/GenotypeRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/VariantContextRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/VariantRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/serialization/ADAMKryoRegistrator.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/InnerTreeRegionJoinSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/RightOuterTreeRegionJoinSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/TreeRegionJoinSuite.scala
pom.xml
scripts/move_to_scala_2.10.sh
scripts/move_to_scala_2.11.sh

Resolves #1334. Eliminates type erasure problems by having different concrete implementations per each broadcast. Depends on https://github.com/bigdatagenomics/utils/pull/97.

[ADAM-1334] Clean up serialization issues in Broadcast region join.

---

docs/source/50_cli.md

Resolves #1342. Adds validation stringency documentation for vcf2adam and adam2vcf. Removes mention of the anno2adam and flatten commands, which were removed in #1288.

[ADAM-1342] Update CLI docs after #1288 merged.

---

adam-cli/src/main/scala/org/bdgenomics/adam/cli/Transform.scala
adam-core/src/main/scala/org/bdgenomics/adam/algorithms/consensus/ConsensusGenerator.scala
adam-core/src/main/scala/org/bdgenomics/adam/algorithms/consensus/ConsensusGeneratorFromKnowns.scala
adam-core/src/main/scala/org/bdgenomics/adam/algorithms/consensus/UnionConsensusGenerator.scala
adam-core/src/main/scala/org/bdgenomics/adam/models/IndelTable.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/realignment/RealignIndels.scala
adam-core/src/main/scala/org/bdgenomics/adam/serialization/ADAMKryoRegistrator.scala
adam-core/src/test/scala/org/bdgenomics/adam/models/IndelTableSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/realignment/RealignIndelsSuite.scala

Resolves #1352:
* Fixed issues with consensus model instantiation.
* Added union consensus model (to support multiple models).
* Cleaned up consensus model documentation.
* Call distinct in IndelRealigner on consensus sequences to eliminate dupes.
* Added test for known indel model. Fixed off by one bug.
* Add test for union model.

[ADAM-1352] Clean up consensus model usage.

---

adam-cli/src/main/scala/org/bdgenomics/adam/cli/Fragments2Reads.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/fragment/FragmentRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/MarkDuplicates.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/SingleReadBucket.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/MarkDuplicatesSuite.scala
docs/source/50_cli.md

Resolves #1302 and #1303. Needs more tests and a Pandoc update. Also, I'm thinking the `reads2fragments` and `fragments2reads` CLIs should be merged down to a `transformFragments` CLI. Any disagreement?

Support deduping fragments

---

adam-core/src/main/scala/org/bdgenomics/adam/algorithms/consensus/ConsensusGeneratorFromKnowns.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/realignment/RealignIndels.scala
adam-core/src/test/scala/org/bdgenomics/adam/algorithms/consensus/ConsensusGeneratorFromKnownsSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/realignment/RealignIndelsSuite.scala

Fixes #1362:
* Adding ConsensusGeneratorFromKnownsSuite.
* ConsensusGeneratorFromKnowns drops any targets that did not get hit with any reads, instead of trying to identify the full reference region overlapped by reads. While this case (target with no reads) cannot happen in the FromReads consensus model, it can happen in the FromKnowns model (e.g., use all known INDELs from 1000G with a WES dataset).
* Additionally, tracked down a minor off by one bug in RealignIndels that caused one index in the consensus sequence to not get tested. This could cause reads that aligned to the end of the target to not get realigned.
* To improve legibility, broke up a set of long lines in RealignIndels.

[ADAM-1362] Fixing issue where FromKnowns consensus model fails if no reads hit a target.

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/MDTagging.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/MDTaggingSuite.scala

Resolves #1365. If a read is mapped to a contig that is missing from the broadcasted fragment map, we look at the user's provided validation stringency before throwing an exception.

[ADAM-1365] Apply validation stringency to reads on missing contigs when MD tagging

---

adam-core/src/main/scala/org/bdgenomics/adam/converters/DefaultHeaderLines.scala
adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/ADAMVCFOutputFormat.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/GenotypeRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/VariantContextRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/VariantRDD.scala
adam-core/src/test/scala/org/bdgenomics/adam/converters/VariantContextConverterSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/models/ReferenceRegionSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDDSuite.scala

[ADAM-1372] Increase visibility for DefaultHeaderLines.allHeaderLines

---

adam-cli/src/main/scala/org/bdgenomics/adam/cli/Transform.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/fragment/FragmentRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDD.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/MarkDuplicatesSuite.scala

Resolves #1092. Prior to this, javac would not recognize the AlignmentRecordRDD trait as extending GenomicRDD. Done in two commits, as I'd like to pick the commit that makes AlignmentRecordRDD concrete over to 0.21.1, but I'd rather not delete the (Un)AlignedReadRDD classes on 0.21.1.

Make javac see that AlignmentRecordRDD extends GenomicRDD

---

adam-core/src/main/java/org/bdgenomics/adam/io/FastqRecordReader.java

To fix #1393, don't double count the length of the readname line. In addition, to prevent the length of a line is longer than MAX_LINE_LENGTH in https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/java/org/bdgenomics/adam/io/FastqRecordReader.java#L330

[ADAM-1393] fix missing reads when transforming fastq to adam

---

adam-core/src/main/java/org/bdgenomics/adam/io/InterleavedFastqInputFormat.java
adam-core/src/main/java/org/bdgenomics/adam/io/SingleFastqInputFormat.java

[ADAM-1383] Use gt instead of gteq in FASTQ input format line size checks

---

adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala
adam-core/src/test/scala/org/bdgenomics/adam/converters/VariantContextConverterSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/ADAMContextSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/variant/VariantContextRDDSuite.scala

Resolves #1381. Sets variant end position to the proper site for symbolic alleles.

[ADAM-1381] Fix Variant end position.

---

adam-cli/src/main/java-templates/org/bdgenomics/adam/cli/About.java
adam-cli/src/main/scala/org/bdgenomics/adam/cli/ADAMMain.scala
adam-cli/src/test/scala/org/bdgenomics/adam/cli/AboutSuite.scala

Commit cherry picked from pull request #1360

Add Apache Spark version to --version text

---

adam-core/src/main/scala/org/bdgenomics/adam/instrumentation/Timers.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/GenomicRDD.scala

Had this on my branch testing #1324 with the INDEL realigner. Thought it was more generally useful.

Added instrumentation timers around joins.

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/FeatureParser.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/FeatureRDD.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/feature/FeatureRDDSuite.scala

Split from #1378 for easier review and merge.  Fixes #1409, fixes #1410.

Estimate contig lengths in SequenceDictionary for BED, GFF3, GTF, and NarrowPeak feature formats

---

adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala

Resolves #1371. Could use some more unit tests; will make a pass back later.

[ADAM-1371] Wrap ADAM->htsjdk VariantContext conversion with validation stringency.

---

adam-core/src/main/scala/org/bdgenomics/adam/util/TwoBitFile.scala

Rewrite the extract logic.
On a single node with 20 workers, BaseRecalibration time is reduced from 5.8 min to 1.7 min.
Pass existing tests.

feat: speed up 2bit file extract

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/BEDInFormatter.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/BEDOutFormatter.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/GFF3InFormatter.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/GFF3OutFormatter.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/GTFInFormatter.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/GTFOutFormatter.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/NarrowPeakInFormatter.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/NarrowPeakOutFormatter.scala
adam-core/src/test/resources/dvl1.200.gtf
adam-core/src/test/scala/org/bdgenomics/adam/rdd/feature/FeatureRDDSuite.scala
docs/source/60_building_apps.md

Work in progress, opened pull request for review.
Fixes #1374

Add pipe API in and out formatters for Features

---

adam-cli/src/main/scala/org/bdgenomics/adam/cli/TransformFeatures.scala
adam-core/src/main/scala/org/bdgenomics/adam/instrumentation/Timers.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/FeatureRDD.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/ADAMContextSuite.scala

Add cache argument to loadFeatures, additional Feature timers

---

adam-apis/src/main/scala/org/bdgenomics/adam/apis/java/JavaADAMContext.scala
adam-apis/src/test/java/org/bdgenomics/adam/apis/java/JavaADAMCoverageConduit.java
adam-apis/src/test/scala/org/bdgenomics/adam/apis/java/JavaADAMContextSuite.scala
adam-core/src/test/resources/sample_coverage.bed
adam-core/src/test/scala/org/bdgenomics/adam/rdd/feature/CoverageRDDSuite.scala

Resolves https://github.com/bigdatagenomics/adam/issues/1420

added JavaApi for loadCoverage

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/FileMerger.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/ParallelFileMerger.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/ShuffleRegionJoin.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/FeatureRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/VariantContextRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/serialization/ADAMKryoRegistrator.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/FileMergerSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/ParallelFileMergerSuite.scala

Resolves #1164. I'd actually love to get this into 0.22.0 as well. Thoughts?

[ADAM-1164] Add parallel file merger.

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/GenomicRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/OutFormatter.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AnySAMOutFormatter.scala

Resolves #1442. Eliminates use of thread pool in GenomicRDD and instead launches the InFormatterRunner (which extends `Callable`) as a thread and runs the OutFormatterRunner in the original thread that launched the piped subprocess.
Additionally, rewrote the `AnySAMOutFormatter` to improve performance.
With this, BWA-on-Cannoli works (https://github.com/heuermh/cannoli/pull/2).

[ADAM-1442] Fix thread pool deadlock in GenomicRDD.pipe

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/fragment/FragmentRDD.scala

[ADAM-1445] Make apply method for FragmentRDD public.

---

adam-cli/src/main/scala/org/bdgenomics/adam/cli/TransformFeatures.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/FeatureRDD.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/ADAMContextSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/feature/CoverageRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/feature/FeatureRDDSuite.scala

[ADAM-1439] Add inferSequenceDictionary ctr to FeatureRDD.

---

adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala

[ADAM-1451] Make VariantContextConverter class and convert methods public

---

adam-core/src/main/java/org/bdgenomics/adam/io/InterleavedFastqInputFormat.java
adam-core/src/main/java/org/bdgenomics/adam/io/SingleFastqInputFormat.java

[ADAM-1459] Don't split FASTQ when compressed.

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/TreeRegionJoin.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/contig/NucleotideContigFragmentRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/CoverageRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/FeatureRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/fragment/FragmentRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/RepairPartitions.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/GenotypeRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/VariantContextRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/VariantRDD.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/RepairPartitionsSuite.scala
pom.xml

On top of #1360. Potential fix for the flagging unit test issues in #1324 and #1360. See https://github.com/bigdatagenomics/utils/pull/116. CC @heuermh @devin-petersohn

Dependency version bump + BroadcastRegionJoin fix

---

docs/source/50_cli.md

[ADAM-1465] Updating realigner CLI docs.

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/ParallelFileMerger.scala

[ADAM-1467] Skip `concat` call if there is only one shard.

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/realignment/RealignIndels.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/realignment/RealignIndelsSuite.scala

Resolves #1469. Provides approximately a 1% bump in both INDEL calling precision and recall.

[ADAM-1469] Don't filter on whether reads have mismatches during realignment

---

adam-core/src/main/scala/org/bdgenomics/adam/models/Coverage.scala
adam-core/src/test/scala/org/bdgenomics/adam/models/CoverageSuite.scala

Adding require for Coverage Conversion and related tests

---

adam-apis/pom.xml
adam-assembly/pom.xml
adam-cli/pom.xml
adam-cli/src/test/resources/log4j.properties
adam-core/pom.xml
adam-core/src/test/resources/log4j.properties
pom.xml
scripts/move_to_scala_2.11.sh

Notes to self:
* https://github.com/HadoopGenomics/Hadoop-BAM/compare/7.7.0...7.7.1
* https://github.com/apache/avro/compare/release-1.8.0...release-1.8.1
* https://github.com/apache/avro/compare/release-1.8.1...release-1.8.2-rc1
* https://github.com/qos-ch/slf4j/compare/v_1.7.21...v_1.7.22
* slf4j-log4j12 is compile scoped in adam-core, that doesn't seem correct
* args4j version 2.32 is not binary compatible with 2.0.31, fix upstream in utils, may require code changes
* scoverage 1.1.1 to 1.3.0, see issue https://github.com/bigdatagenomics/utils/issues/95
* servo dependency was reported unused; older version declared in utils-metrics, may be req'd for guava exclusion
* update htsjdk 2.5.0 to 2.8.1 in separate commit, to isolate any issues
* guava is still stuck by hadoop as far as I …

Update dependency and plugin versions

---

adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala
adam-core/src/test/resources/test.vcf
adam-core/src/test/scala/org/bdgenomics/adam/rdd/ADAMContextSuite.scala

[ADAM-1476] Treat `.` ALT allele as symbolic non-ref.

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala

[ADAM-1456] Remove .{type}.adam file extension conversions in type-guessing methods.

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/recalibration/RecalibrationTable.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/recalibration/Recalibrator.scala

[ADAM-1488] Only increment BQSR min quality by 33 once.

---

adam-apis/src/test/java/org/bdgenomics/adam/apis/java/JavaADAMCoverageConduit.java
adam-apis/src/test/java/org/bdgenomics/adam/apis/java/JavaADAMFeatureConduit.java
adam-cli/src/main/scala/org/bdgenomics/adam/cli/ADAM2Vcf.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/Fragments2Reads.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/Reads2Coverage.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/Reads2Fragments.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/Transform.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/TransformFeatures.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/View.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMRDDFunctions.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/FileMerger.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/GenomicRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/CoverageRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/FeatureRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/VariantContextRDD.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/ADAMContextSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/feature/CoverageRDDSuite.scala
docs/source/50_cli.md

[ADAM-1480] Add switch to disable the fast concat method.

---

adam-core/src/main/scala/org/bdgenomics/adam/models/ReferenceRegion.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/ReferencePositionPair.scala
adam-core/src/test/scala/org/bdgenomics/adam/models/ReferenceRegionSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/MarkDuplicatesSuite.scala

Partially resolves #1473 and fully resolves #1474.

Clean up ReferenceRegion.scala and add thresholded overlap and covers

---

adam-core/src/main/scala/org/bdgenomics/adam/converters/AlignmentRecordConverter.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/fragment/FragmentRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/fragment/Tab6InFormatter.scala
adam-core/src/test/resources/tab6_to_usam.py
adam-core/src/test/scala/org/bdgenomics/adam/rdd/fragment/FragmentRDDSuite.scala

Fixes #1377.  Work in progress, need to write tests and eliminate copy-pasta.

[ADAM-1377] Adding fragment InFormatter for Bowtie tab6 format

---

adam-core/src/main/scala/org/bdgenomics/adam/util/TwoBitFile.scala
adam-core/src/test/scala/org/bdgenomics/adam/util/TwoBitFileSuite.scala

Resolves #1502.
@tomwhite this should resolve the issue you were seeing. Can you test this out on your end?

[ADAM-1502] Preserve contig ordering in TwoBitFile sequence dictionary.

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/TreeRegionJoin.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/TreeRegionJoinSuite.scala

Making TreeRegionJoin consistent with ShuffleRegionJoin

---

adam-cli/src/main/scala/org/bdgenomics/adam/cli/Reads2Coverage.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/CoverageRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDD.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDDSuite.scala
docs/source/50_cli.md

Resolves #1483. Instead of providing a parameter in the `toCoverage` method to allow users to collapse the coverage, makes the `toCoverage` method stupid. This makes the `toCoverage` method simpler and the behavior easier to reason about.

[ADAM-1483] Remove collapse parameter from AlignmentRecordRDD.toCoverage

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/GenomicRDD.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/GenomicRDDSuite.scala

Resolves #1508, #1509. WIP, still being tested.

Resolve #1508, #1509 for Pipe API

---

adam-cli/src/main/scala/org/bdgenomics/adam/cli/Transform.scala
adam-cli/src/test/scala/org/bdgenomics/adam/cli/TransformSuite.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/fragment/FragmentRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/BinQualities.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/fragment/FragmentRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/BinQualitiesSuite.scala
docs/source/50_cli.md

Resolves #1462. WIP. Still need to:

Add quality score binner

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/FeatureRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/GFF3HeaderWriter.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/feature/FeatureRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/feature/GFF3HeaderWriterSuite.scala

[ADAM-1169] Write GFF header line pragma in single file mode.

---

adam-core/src/main/scala/org/bdgenomics/adam/models/RecordGroupDictionary.scala
adam-core/src/main/scala/org/bdgenomics/adam/models/SequenceDictionary.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/GenomicRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/contig/NucleotideContigFragmentRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/CoverageRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/FeatureRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/fragment/FragmentRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/GenotypeRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/VariantContextRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/VariantRDD.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/contig/NucleotideContigFragmentRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/feature/CoverageRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/feature/FeatureRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/fragment/FragmentRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/variant/GenotypeRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/variant/VariantContextRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/variant/VariantRDDSuite.scala

Resolves #1497. Also adds `size` methods to `SequenceDictionary` and `RecordGroupDictionary`. Requires the addition of a `ClassTag` to the `GenericGenomicRDD` case class.

[ADAM-1497] Add union to GenomicRDD.

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/GenomicRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/TreeRegionJoin.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDDSuite.scala
docs/source/55_api.md
pom.xml

[ADAM-1499] Enable reuse of broadcasted objects in region join.

---

adam-apis/src/main/scala/org/bdgenomics/adam/apis/java/JavaADAMContext.scala
adam-apis/src/test/scala/org/bdgenomics/adam/apis/java/JavaADAMContextSuite.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala

Resolves #1421. Also fixes `JavaADAMContextSuite` to actually use `JavaADAMContext` instead of `ADAMContext`.

[ADAM-1421] Add java API for `loadReferenceFile`.

---

adam-assembly/pom.xml
bin/adam-shell
bin/adam-submit

[ADAM-1361] Fix misnamed ADAM überjar.

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/GenomicRDD.scala

[ADAM-1549] Make regions provided to filterByOverlappingRegions an Iterable.

---

adam-core/src/main/scala/org/bdgenomics/adam/converters/AlignmentRecordConverter.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/fragment/Tab5InFormatter.scala
adam-core/src/test/resources/tab5_to_usam.py
adam-core/src/test/scala/org/bdgenomics/adam/rdd/fragment/FragmentRDDSuite.scala

I was mistaken earlier that supporting tab6 would be sufficient for bowtie and bowtie2 support in cannoli.  Tab5 format is req'd for the bowtie `--12` argument.
See https://github.com/bigdatagenomics/cannoli/issues/33

Adding fragment InFormatter for Bowtie tab5 format

---

adam-core/src/main/scala/org/bdgenomics/adam/models/SequenceDictionary.scala
adam-core/src/main/scala/org/bdgenomics/adam/models/SnpTable.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMInputFormat.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMParquetInputFormat.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/GenomicRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/ManualRegionPartitioner.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/ShuffleRegionJoin.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/contig/NucleotideContigFragmentRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/CoverageRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/FeatureRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/fragment/FragmentRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/GenotypeRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/VariantContextRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/VariantRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/serialization/ADAMKryoRegistrator.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/InnerShuffleRegionJoinSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/LeftOuterShuffleRegionJoinSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/SortedGenomicRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/feature/CoverageRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/feature/FeatureRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/fragment/FragmentRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/realignment/RealignIndelsSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/variant/GenotypeRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/variant/VariantContextRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/variant/VariantRDDSuite.scala
docs/source/70_algorithms.md

Efficient Joins and (re)Partitioning

---

adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala
adam-core/src/test/scala/org/bdgenomics/adam/converters/VariantContextConverterSuite.scala

[ADAM-1562] Index off by one for VCF genotype Number=A attributes.

---

pom.xml

Sorry @heuermh, I accidentally left this change out...

Bump bdg-formats correctly to 0.11.1, not SNAPSHOT.

---

adam-core/src/main/scala/org/bdgenomics/adam/projections/Projection.scala
adam-core/src/test/scala/org/bdgenomics/adam/projections/AlignmentRecordFieldSuite.scala

[ADAM-1417] Removed unused Projection.apply method, add test for Filter.

---

pom.xml

Resolves #1444. Bumps to latest version of coveralls plugin and sets `failOnServiceError`, which ignores internal errors in Coveralls when pushing.

[ADAM-1444] Ignore failed push to Coveralls.

---

adam-apis/src/test/java/org/bdgenomics/adam/api/java/JavaADAMContigConduit.java
adam-core/src/main/scala/org/bdgenomics/adam/rdd/GenomicRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/contig/NucleotideContigFragmentRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/FeatureRDD.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/contig/NucleotideContigFragmentRDDSuite.scala

Resolves #1438. To support saving FASTA as a single file, moved the private `writeTextRdd` method from the `FeatureRDD` to `GenomicRDD`, and opened protections to `protected`.

[ADAM-1438] Add ability to save FASTA back as a single file.

---

adam-cli/src/main/scala/org/bdgenomics/adam/cli/Reads2Coverage.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDD.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDDSuite.scala

Resolves #1501. Depends on #1391. Perf numbers forthcoming.

[ADAM-1501] Compute coverage using Dataset API.

---

adam-core/src/main/scala/org/bdgenomics/adam/models/RecordGroupDictionary.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/GenomicRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/contig/NucleotideContigFragmentRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/CoverageRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/FeatureRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/fragment/FragmentRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/GenotypeRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/VariantContextRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/VariantRDD.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/contig/NucleotideContigFragmentRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/feature/CoverageRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/feature/FeatureRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/fragment/FragmentRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/variant/GenotypeRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/variant/VariantContextRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/variant/VariantRDDSuite.scala

Resolves #1599. Adds functions that replaces or appends to the sequence dictionary/record groups/header lines/sample metadata that is attached to a GenomicRDD. This is necessary as a59b8ed948db1bbf50260a61ed404b8325df0563 eliminated the `copy` methods that were attached to all implementations of `GenomicRDD` by making the exposed implementations abstract classes instead of case classes.
~One TODO:~

[ADAM-1599] Add explicit functions for updating GenomicRDD metadata.

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/VCFHeaderUtils.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/ADAMVCFOutputFormat.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/GenotypeRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/VariantContextRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/VariantRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/util/FileExtensions.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/variant/VariantContextRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/util/FileExtensionsSuite.scala

Resolves #1554. Additionally:
* Moves VCF file extension logic into ADAM, since Hadoop-BAM does not recognize .bgzf as a valid BGZF extension
* Refactored VCF output formats to remove need for ADAMHeaderlessVCFOutputFormat
This isn't completely done... Specifically, it produces output that bcftools thinks is good:
```
$ bcftools stats bqsr1.vcf.bgz 
#
ID	0	bqsr1.vcf.bgz
SN	0	number of samples:	0
SN	0	number of records:	681
SN	0	number of no-ALTs:	0
SN	0	number of SNPs:	681
SN	0	number of MNPs:	0
SN	0	number of indels:	0
SN	0	number of others:	0
SN	0	number of multiallelic sites:	0
SN	0	number of multiallelic SNP sites:	0
```
But, that fails to load in properly when read back from ADAM:
```
scala> sc.loadVcf("bqsr1.vcf.bgz").rdd.count
res1: Long = 0
```
I'm still debugging this, but was …

[ADAM-1554] Support saving BGZF VCF output.

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/GenomicRDD.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/contig/NucleotideContigFragmentRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/feature/CoverageRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/feature/FeatureRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/fragment/FragmentRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/variant/GenotypeRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/variant/VariantContextRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/variant/VariantRDDSuite.scala
docs/source/55_api.md

Resolves #1576. Adds `transmute` function, which is analogous to `transform`, but which allows any return type. This uses an implicit function a la `pipe` to build the output GenomicRDD.
Can I get a quick review pass on this? If this general direction looks good, I will flesh out the implicits for all the allowable transformations.

[ADAM-1576] Allow translation between two different GenomicRDD types.

---

adam-core/src/main/scala/org/bdgenomics/adam/util/TwoBitFile.scala

[ADAM-1610] Mark non-serializable field in TwoBitFile as transient.

---

adam-apis/src/main/scala/org/bdgenomics/adam/api/java/GenomicRDDConverters.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/GenomicRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/SAMInFormatter.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDDSuite.scala
adam-python/src/bdgenomics/adam/rdd.py
adam-python/src/bdgenomics/adam/test/alignmentRecordRdd_test.py
adam-r/bdg.adam/R/generics.R
adam-r/bdg.adam/R/rdd.R
adam-r/bdg.adam/tests/testthat/test_alignmentRecordRdd.R
docs/source/55_api.md

Resolves #1611. Depends on #1397. Adds a Java-friendly pipe method onto `GenomicRDD`, and     conversion functions in the `org.bdgenomics.adam.api.java` package. Simultaneously, we add a `GenomicRDD` base type in the R bindings. With these additions, we then add the pipe method to the `GenomicRDD` class that exists in both Python and R. The language bindings use reflection     to construct the in/out-formatters and conversion functions.
While I was at it, I also made the `toDF` implementation in R generic.

[ADAM-1611] Extend pipe APIs to Java, Python, and R.

---

docs/source/55_api.md

Adding examples of how to use joins in the real world

---

distribution/src/main/assembly/assembly.xml
scripts/jenkins-test

Resolves #1607. 3ea4f18e2275bdbed7609403098aa4194b03003a renamed the überjar generated by the adam-assembly package from `adam_<version>.jar` to `adam-assembly_<version>.jar`, but did not update the distribution assembly task. This commit updates that task, and adds code to `jenkins-test` to ensure that the assembly jar is packaged in the distribution.

[ADAM-1607] Update distribution assembly task to attach assembly überjar

---

adam-core/pom.xml

[ADAM-1623] Add ProcessingStep to adam-codegen.

---

adam-core/src/main/scala/org/bdgenomics/adam/converters/DefaultHeaderLines.scala

[ADAM-1625] Use explicit types for header lines

---

adam-python/src/bdgenomics/adam/rdd.py
adam-python/src/bdgenomics/adam/test/genotypeRdd_test.py
adam-python/src/bdgenomics/adam/test/variantRdd_test.py
adam-r/bdg.adam/R/generics.R
adam-r/bdg.adam/R/rdd.R
adam-r/bdg.adam/tests/testthat/test_genotypeRdd.R
adam-r/bdg.adam/tests/testthat/test_variantRdd.R

Resolves #1614. Restructures both R and Python APIs to add `GenomicDataset` class, which inherits from `GenomicRDD`, as in adam-core. Moves all implementing classes onto `GenomicDataset`, and adds `VariantContextRDD` which is the lone class that extends `GenomicRDD`. Deletes `saveAsVcf` from `GenotypeRDD` and `VariantRDD`, and moves this functionality into `toVariantContextRDD` functions and `VariantContextRDD.saveAsVcf`. Additionally, adds `sort` and `sortLexicographically` to the R API, and fixes `sortLexicographically` in the Python API (it was calling `sort` previously).

[ADAM-1614] Add VariantContextRDD to R and Python APIs.

---

adam-core/src/main/java/org/bdgenomics/adam/io/FastqInputFormat.java
adam-core/src/main/java/org/bdgenomics/adam/io/FastqRecordReader.java

Resolves #1635. Instead of passing whether a FASTQ was splittable via config, checks to see if the compression codec is splittable. This is more reliable. In the case of a .gz file, the BGZFEnhancedGZipCodec properly handles this edge case by checking the stream type; this coupled with us explicitly checking the stream when split picking ensures that we don't try to create an invalid GZIP split. Additionally, I identified and fixed an error in the old FASTQ code that did a seek on the uncompressed input stream to backtrack if seeing a line of quality scores that began with @ when identifying the position of the first valid record in a split. Instead, we check for two successive lines that start with an @, which indicates that the first line contains quality scores, while the second line …

[ADAM-1635] Eliminate passing FASTQ splittable status via config.

---

adam-apis/src/main/scala/org/bdgenomics/adam/api/java/GenomicDatasetConverters.scala
adam-apis/src/main/scala/org/bdgenomics/adam/api/python/DataFrameConversionWrapper.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/GenomicDatasetConversion.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/GenomicRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/contig/NucleotideContigFragmentRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/CoverageRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/FeatureRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/fragment/FragmentRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/GenotypeRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/VariantRDD.scala
adam-python/src/bdgenomics/adam/rdd.py
adam-python/src/bdgenomics/adam/test/alignmentRecordRdd_test.py
adam-r/bdg.adam/R/generics.R
adam-r/bdg.adam/R/rdd.R
adam-r/bdg.adam/tests/testthat/test_alignmentRecordRdd.R

Resolves #1615. Adds `GenomicDatasetConversion` class to adam-core API, along with accompanying implementations in `org.bdgenomics.adam.api.java` package. Adds `transformDataFrame` and `transmuteDataFrame` to `GenomicRDD` API. To enable use from Python and R, we provide a `DataFrameConversionWrapper` that wraps the product of an R/Python function in a Spark Java API `Function`.

[ADAM-1615] Add transform and transmute APIs to Java, R, and Python

---

docs/source/60_building_apps.md

Resolves #1638.
Wrapped lines at 80 if possible, also addressed formatting and spacing issues from rendering of the doc.

Cleaning up formatting and spacing of docs.

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/contig/NucleotideContigFragmentRDD.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/contig/NucleotideContigFragmentRDDSuite.scala

I added extract regions functions as extracting not one, but many regions at the same time is quite common use-case (I had to do it a lot).

added ExtractRegions

---

adam-core/src/main/scala/org/bdgenomics/adam/models/RecordGroupDictionary.scala
adam-core/src/test/scala/org/bdgenomics/adam/models/RecordGroupDictionarySuite.scala

Resolves #1663. When unioning two read groups together, calls distinct after appending the two RecordGroupDictionaries.

[ADAM-1663] Enable read groups with repeated names when unioning.

---

adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala
adam-core/src/test/resources/gvcf_dir/gvcf_multiallelic_noPLs.g.vcf
adam-core/src/test/scala/org/bdgenomics/adam/rdd/ADAMContextSuite.scala

[ADAM-1673] Don't set PL to empty when no PL is attached to a gVCF record

---

adam-core/src/main/scala/org/bdgenomics/adam/instrumentation/Timers.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/VariantContextRDD.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/variant/VariantContextRDDSuite.scala

[ADAM-1693] Add adam-shell friendly VariantContextRDD.saveAsVcf method.

---

pom.xml

[ADAM-1688] Add bdg-formats exclusion to org.hammerlab:genomic-loci dependency.

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/GenomicRDD.scala

[ADAM-1694] Add short readable descriptions for toString in subclasses of GenomicRDD.

---

adam-core/src/main/scala/org/bdgenomics/adam/algorithms/consensus/NormalizationUtils.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDD.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDDSuite.scala

Resolves #1709. Opens protection on main method in NormalizationUtils to be package-private to org.bdgenomics.adam. Adds code to AlignmentRecordRDD exposing INDEL normalization as a transformation.

[ADAM-1709] Add ability to left normalize reads containing INDELs.

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/fragment/InterleavedFASTQInFormatter.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AnySAMOutFormatter.scala

Misc cleanup needed for bigdatagenomics/cannoli#65

---

adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala
adam-core/src/test/scala/org/bdgenomics/adam/converters/VariantContextConverterSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/variant/VariantContextRDDSuite.scala

Resolves #1676. Pushes validation checking down to the single field conversion level, which keeps a variant/genotype record around even if a bad INFO/FORMAT field was attached to that record.
WIP, needs more testing, not ready for merge.

[ADAM-1676] Add more finely grained validation for INFO/FORMAT fields.

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/GenomicRDD.scala

Making join return types consistent

---

adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala
adam-core/src/main/scala/org/bdgenomics/adam/serialization/ADAMKryoRegistrator.scala
adam-core/src/test/resources/HG001_GRCh38_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-X_v.3.3.2_all.fixed-phase-set.excerpt.vcf
adam-core/src/test/resources/HG001_GRCh38_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-X_v.3.3.2_all.fixed-phase-set.excerpt.vcf.README
adam-core/src/test/scala/org/bdgenomics/adam/rdd/ADAMContextSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/variant/VariantContextRDDSuite.scala

[ADAM-1695] Check for illegal genotype index after splitting multi-allelic variants.

---

adam-core/src/main/scala/org/bdgenomics/adam/models/ReferenceRegion.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/GenomicRDD.scala
adam-core/src/test/scala/org/bdgenomics/adam/models/ReferenceRegionSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/LeftOuterShuffleRegionJoinSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/SortedGenomicRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/feature/FeatureRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/fragment/FragmentRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/variant/GenotypeRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/variant/VariantRDDSuite.scala

Enabled thresholding for joins and standardized regionFn

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/GenomicRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/ShuffleRegionJoin.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/LeftOuterShuffleRegionJoinAndGroupByLeftSuite.scala

Resolves #1745. Depends on #1741 .

Issue#1745 left outer group by left

---

adam-apis/src/main/scala/org/bdgenomics/adam/api/java/JavaADAMContext.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala
adam-python/bdgenomics/adam/adamContext.py
adam-r/bdg.adam/R/adam-context.R
adam-r/bdg.adam/R/generics.R

Resolves #1715. Also adds support for validation stringency when loading fragments.

[ADAM-1715] Support validation stringency in Python/R.

---

adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala
adam-core/src/test/resources/inf_float_values.vcf
adam-core/src/test/scala/org/bdgenomics/adam/converters/VariantContextConverterSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/ADAMContextSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/variant/VariantContextRDDSuite.scala

Resolves #1512. @heuermh do you have any VCFs that reproduce this issue? It would be good to add a test resource, if we've got one.

[ADAM-1512] Support VCFs with +Inf/-Inf float values.

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/realignment/IndelRealignmentTarget.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/realignment/IndelRealignmentTargetSuite.scala

Resolves #1753. Not ready for merge, still validating.

[ADAM-1753] Only emit realignment targets for reads containing a single INDEL

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/GenomicRDD.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/SortedGenomicRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDDSuite.scala

Resolves #1680. In the existing shuffle region join code, the partition start/stop boundaries are determined by sorting the data and looking at the coordinates of the first and last record on each partition. This is done via a sampling process, which is fundamentally non-deterministic. Once these partition bounds are picked, we replicate records from the right side of the join into the partitions they overlap. There was a bug in this step that led to records being dropped from the first partition of each contig (except for the first contig). This was due to a bug in how the IntervalArray was being used to search for repartitioning bounds.
This PR replaces the interval array with a map between contig names and the partitions that contain their data. The first and last partition of each …

[ADAM-1680] Eliminate non-determinism in the ShuffleRegionJoin.

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/ADAMContextSuite.scala

Resolves #1670. Adds a method loadVcfWithProjection to ADAMContext. This method takes a list of INFO/FORMAT field names, which are then applied as filters to the set of header lines used when creating the VariantContextConverter.

[ADAM-1670] Add ability to selectively project VCF fields.

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/FASTQInFormatter.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDDSuite.scala

Resolves #1768. Still testing; not ready for merge. Thoughts on how to handle the configuration properties that are shared with `InterleavedFASTQInFormatter`? I'd rather not duplicate them.

[ADAM-1768] Add InFormatter for unpaired FASTQ.

---

adam-apis/pom.xml
adam-cli/pom.xml
adam-core/pom.xml
pom.xml

Resolves #1789. Also includes utils-misc in adam-core. Previously, utils-misc was specified as just being test scoped in adam-core.

[ADAM-1789] Move scala-lang to provided scope.

---

adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala

[ADAM-1770] Genotype should only store core variant fields.

---

adam-distribution/src/main/assembly/assembly.xml
adam-r/bdgenomics.adam/DESCRIPTION
adam-r/pom.xml
docs/source/02_installation.md

Add R and Python into distribution artifacts

---

adam-r/pom.xml

[ADAM-1672] Use working directory for R devtools::document().

---

adam-python/pom.xml
adam-r/pom.xml

[ADAM-1795] Map -DskipTests=true to exec.skip for Python and R tests.

---

docs/vendor/sphinxcontrib/fulltoc.py

[ADAM-1821] Add missing fulltoc for Sphinx documentation.

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/ADAMBAMOutputFormat.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/ADAMCRAMOutputFormat.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/ADAMSAMOutputFormat.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/util/ParallelFileMergerSuite.scala

[ADAM-1834] Add proper extensions for SAM/BAM/CRAM output formats.

---

adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/VCFInFormatter.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/VCFOutFormatter.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/VariantContextRDD.scala
adam-core/src/test/scala/org/bdgenomics/adam/converters/VariantContextConverterSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/models/ReferenceRegionSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/variant/VariantContextRDDSuite.scala

Resolves #1838. Modifies the behavior of #1771, which disabled populating the `variant.annotation` field in the `Genotype` record. Now, this field is not populated by default. To enable populating it, a user can set the property `org.bdgenomics.adam.converters.VariantContextConverter.NEST_ANN_IN_GENOTYPES` to true.

[ADAM-1838] Make populating variant.annotation field in Genotype configurable

---

scripts/release/release.sh

Opened a new branch for updates to the release script.
I'm not confident this will work, the build from source instructions look for the assembly jar relative to an `${ADAM_HOME}`, which will keep moving during a release build (once at the normal depth and then nested for the build from the checked out release tag)
```
ASSEMBLY_DIR="${ADAM_HOME}/adam-assembly/target"
ASSEMBLY_JAR="$(ls -1 "$ASSEMBLY_DIR" | grep "^adam[0-9A-Za-z\.\_-]*\.jar$" | grep -v -e javadoc -e sources || true)"
export PYSPARK_SUBMIT_ARGS="--jars ${ASSEMBLY_DIR}/${ASSEMBLY_JAR} --driver-class-path ${ASSEMBLY_DIR}/${ASSEMBLY_JAR} pyspark-shell"
```
```
ASSEMBLY_DIR="${ADAM_HOME}/adam-assembly/target"
ASSEMBLY_JAR="$(ls -1 "$ASSEMBLY_DIR" | grep "^adam[0-9A-Za-z\_\.-]*\.jar$" | grep -v javadoc | grep -v sources || …
```

Remove python and R profiles from release script

---

adam-python/bdgenomics/adam/rdd.py

[ADAM-1858] Use getattr instead of Class.forName from python API.

---

adam-python/version.py
scripts/jenkins-test

Resolves #1871. Also adds a loop to the `jenkins-test` script to test both Python 2.7 and 3.6.

[ADAM-1871] Fix print call that broke python 3 support.

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/ADAMContextSuite.scala

Resolves #1874. While samples should be unique in a single VCF, we may load data from multiple VCFs that contain the same samples (e.g., VCFs from a single sequencing project where the VCFs are split by chromosome). This change dedupes sample IDs on load.

[ADAM-1874] Dedupe samples when loading VCFs.

---

README.md
docs/index.rst

Fixes #1832.
Would require migrating https://github.com/heuermh/awesome-adam to bigdatagenomics organization.

[ADAM-1832] Use awesome list style and link to bigdatagenomics/awesome-adam.

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/GenomicRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/OutFormatter.scala
adam-core/src/test/resources/timeout.py
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDDSuite.scala

Resolves #1875. Adds an optional timeout parameter to the `GenomicRDD.pipe` function. If this is provided, a command will be killed (but without failing the Spark task) if it runs for longer than the timeout parameter.

[ADAM-1875] Add ability to timeout a piped command.

---

bin/find-adam-home

[ADAM-1882] Don't abort adam-submit if ADAM_HOME is set.

---

adam-core/src/main/scala/org/bdgenomics/adam/serialization/ADAMKryoRegistrator.scala

Adds Kryo registration for two classes which is are required for Spark 2.3.0.rc2
With these changes ADAM compiles and passes all tests for Spark-2.3.0.rc2
~~These changes fail to compile with Spark-2.2.1, so must be accompanied by Spark version bump.~~
If there is a better way to note these changes than a PR against master, let me know.

Update for  Spark version 2.3.0

---

docs/conf.py

[ADAM-1917] Load sphinxcontrib.fulltoc with imp.load_sources.

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/GenomicRDD.scala

`SparkFiles.getRootDirectory` appears to be set correctly in local mode even if `SparkEnv.get.driverTmpDir` is not.
Changing the fallback here appears to help https://github.com/bigdatagenomics/cannoli/pull/107 work in local mode.

Use SparkFiles.getRootDirectory in local mode.

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/GenomicRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/GenotypeRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/VariantContextRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/VariantRDD.scala
adam-python/bdgenomics/adam/rdd.py
adam-python/bdgenomics/adam/test/genotypeRdd_test.py

Resolves #1840. Split header line functionality out into VCFSupportingGenomicRDD trait, which has a Scala/Java API for adding header lines. This is then mirrored in Python.

[ADAM-1840] Support adding VCF header lines from Python.

---

adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala
adam-core/src/test/scala/org/bdgenomics/adam/converters/VariantContextConverterSuite.scala

Ignores, and logs a warning, for  non-specifically-supported INFO fields with Number=G when Stringency = LENIENT
rather than  the current behavior of throwing IllegalArgumentException
Needed because I want to be able to parse directly the gnomAD VCF file contains tags such as:
```
INFO=<ID=GC_Male,Number=G,Type=Integer,Description="Count of Male individuals for each genotype">
```
These INFO number=G tags don't have a simple/general  meaning for multi-allelic variants which are split when loaded to ADAM, which is why in status quo this produces `IllegalArgumentException("Number=G INFO lines are not supported in split-allelic model: %s".` 
Simply allowing the user to choose to ignore INFO tags of number=G seems a workable solution to me.
Aside: 
At the least, there is not a general …

Ignore VCF INFO fields with number=G when stringency=LENIENT

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/ADAMContextSuite.scala

[ADAM-1932] Throw file not found exception if directory is empty.

---

pom.xml

[ADAM-1931] Bump to Spark 2.3.0.

---

docs/requirements.txt

Move fulltoc below the specific Sphinx version in requirements.txt. Resolves #1917?

[ADAM-1917] Try 3: fix Sphinx fulltoc.

---

scripts/jenkins-test
scripts/release/release.sh

[ADAM-1914] Python profile needs to be specified for egg to be in distribution.

---

adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala
adam-core/src/main/scala/org/bdgenomics/adam/util/PhredUtils.scala

Resolves #1957. Introduces a PhredUtils maximum value constant.

[ADAM-1957] Don't initialize missing likelihoods to MinValue.

---

adam-core/src/main/scala/org/bdgenomics/adam/util/ADAMShell.scala

E.g.
```
scala> import org.bdgenomics.adam.rdd.ADAMContext._
import org.bdgenomics.adam.rdd.ADAMContext._
scala> import org.bdgenomics.adam.util.ADAMShell._
import org.bdgenomics.adam.util.ADAMShell._
scala> val variants = sc.loadVariants("Mills_and_1000G_gold_standard.indels.variants.adam")
variants: org.bdgenomics.adam.rdd.variant.VariantRDD = ParquetUnboundVariantRDD with 3366 reference sequences
scala> printVariantFilters(variants)
Filter Header Lines
FILTER=<ID=PASS,Description="Truth sensitivity tranche level at VQS Lod < -381.3592">
Variant Filters
+-------------+--------+--------+-------+--------+-----------------+----------------+----------------+
| Contig Name | Start  |  End   |  Ref  |  Alt   | Filters Applied | Filters Passed | Filters Failed | …
```

Add utility methods for adam-shell

---

README.md

[ADAM-1976] Adding core API documentation link and badge.

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/GenomicRDD.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDDSuite.scala

 Fix partitioning code to use Long instead of Int

---

adam-codegen/src/main/scala/org/bdgenomics/adam/codegen/DumpSchemasToProduct.scala

For user convenience when working with scala

Set defaults to schemas

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/GenomicRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/contig/NucleotideContigFragmentRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/FeatureRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/fragment/FragmentRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/GenotypeRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/VariantContextRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/VariantRDD.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/variant/VariantContextRDDSuite.scala

[ADAM-1996] Load and save VariantContexts as partitioned Parquet.

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/FeatureRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/GenotypeRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/VariantRDD.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/feature/FeatureRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/variant/GenotypeRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/variant/VariantRDDSuite.scala

Fixes #1978.
Thank you to @antonkulaga, the methods here are inspired by those in
https://github.com/antonkulaga/adam-playground

[ADAM-1978] Add additional filter by convenience methods.

---

adam-core/src/main/scala/org/bdgenomics/adam/instrumentation/Timers.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/ADAMContextSuite.scala

Compare to implementation in #1828.  Thanks to @ffinfo for the suggestion.

Add loadPairedFastqAsFragments method.

---

adam-core/src/main/scala/org/bdgenomics/adam/models/SequenceDictionary.scala
adam-core/src/test/scala/org/bdgenomics/adam/models/SequenceDictionarySuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/contig/NucleotideContigFragmentRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/feature/CoverageRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/feature/FeatureRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/fragment/FragmentRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/variant/GenotypeRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/variant/VariantContextRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/variant/VariantRDDSuite.scala

Fixes #1877.  Work in progress.

[ADAM-1877] Add filterToReferenceName(s) to SequenceDictionary.

---

adam-core/src/main/scala/org/bdgenomics/adam/util/ADAMShell.scala

Adding printAttribute methods for alignment records, features, and samples.

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/realignment/IndelRealignmentTarget.scala

[ADAM-2007] Make IndelRealignmentTarget implement Serializable.

---

scripts/jenkins-test

Spark no longer hosts 2.2.1 [in the Spark mirror.](http://mirrors.ocf.berkeley.edu/apache/spark/) Updating to 2.2.2.

Update Jenkins Spark version to 2.2.2

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/ADAMContextSuite.scala

[ADAM-2032] Add StorageLevel as an optional parameter to loadPairedFastq

---

pom.xml

Dear,
Currently, when trying to build ADAM from sources, maven try to find commons-codec-2.0-SNAPSHOT and fail.
This behavior is due to [jets3t](https://bitbucket.org/jmurty/jets3t). Indeed the project defines a range pulls version.
```xml
<dependency>
<groupId>commons-codec</groupId>
<artifactId>commons-codec</artifactId>
<version>[1.8,2.0)</version>
<scope>compile</scope>
</dependency>
```
This unwanted behavior has been reported and described in the issue [246](https://bitbucket.org/jmurty/jets3t/issues/246/commons-codec-dependency-range-pulls)
This patch set the commons-codec required version to `1.11` which allow building ADAM framework on my computer.

Resolve common-codec dependency

---

adam-core/pom.xml

[ADAM-2047] Use source directory relative to project.basedir for adam codegen.

---

adam-core/src/main/scala/org/bdgenomics/adam/models/RecordGroupDictionary.scala
adam-core/src/test/scala/org/bdgenomics/adam/models/RecordGroupDictionarySuite.scala

Resolves #2064. We were writing the KS (key sequence) read group attribute back into the FO (flow order) attribute. This commit resolves this error and adds a unit test touching all supported @RG attributes.

[ADAM-2064] Avoid collision between @RG FO and KS fields.

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/FeatureRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/Features.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/feature/FeatureRDDSuite.scala

Fixes #2039 
@benwbooth Please let me know if this helps.

[ADAM-2039] Adding support for writing BED format per UCSC definition

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDD.scala
adam-core/src/test/resources/readname_sorted.sam
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDDSuite.scala

Creates function to sort reads by query name, and allows SAM files to be written with all sort orders.

Allow for export of query name sorted SAM files

---

pom.xml

[ADAM-2062] Update Spark version to 2.3.2

---

adam-cli/src/main/scala/org/bdgenomics/adam/cli/ADAMMain.scala
adam-cli/src/test/scala/org/bdgenomics/adam/cli/ADAMMainSuite.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/VCFHeaderUtils.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDD.scala
pom.xml

* htsjdk 2.13.2 &rarr; 2.16.1 required changes to `BlockCompressedOutputStream` ctr calls
* Guice 4.1.0 &rarr; 4.2.1 required `override` annotation to `configure` method
* Guava > 16.0 used to throw runtime exceptions due to classpath conflicts; updating to 27.0-jre seems to work fine now, at least with Hadoop 2.7.5 and Spark 2.3.2
* Hadoop default 2.7.3 &rarr; 2.7.5

Update dependency versions, including htsjdk to 2.16.1 and guava to 27.0-jre

---

adam-python/Makefile
adam-python/bdgenomics/adam/test/__init__.py
adam-python/bdgenomics/adam/test/adamContext_test.py
adam-python/bdgenomics/adam/test/alignmentRecordRdd_test.py
adam-python/bdgenomics/adam/test/coverageRdd_test.py
adam-python/bdgenomics/adam/test/featureRdd_test.py
adam-python/bdgenomics/adam/test/genotypeRdd_test.py
adam-python/bdgenomics/adam/test/variantRdd_test.py
adam-python/setup.py
scripts/jenkins-test

[ADAM-1999] Support Python 3

---

adam-core/src/main/scala/org/bdgenomics/adam/converters/FastqRecordConverter.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/SingleReadBucket.scala
adam-core/src/test/scala/org/bdgenomics/adam/converters/AlignmentRecordConverterSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/converters/FastqRecordConverterSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/contig/NucleotideContigFragmentRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/feature/CoverageRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/feature/FeatureRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/BinQualitiesSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/SingleReadBucketSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/variant/GenotypeRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/variant/VariantRDDSuite.scala
pom.xml

Depends on https://github.com/bigdatagenomics/bdg-formats/pull/162.

Clean up fields and doc in fragment.

---

adam-assembly/pom.xml
adam-cli/pom.xml
adam-cli/src/main/java-templates/org/bdgenomics/adam/cli/About.java
pom.xml

Removes the hack necessary to work around issues with `maven.build.timestamp` property.

Use build-helper-maven-plugin for build timestamp

---

adam-core/pom.xml
adam-core/src/main/scala/org/bdgenomics/adam/models/ReferenceRegion.scala
adam-core/src/test/scala/org/bdgenomics/adam/models/ReferenceRegionSuite.scala
pom.xml

Re-opened to reduce effort when adding Scala 2.12 support.

Remove dependency on org.hammerlab:genomic-loci.

---

adam-apis/src/main/scala/org/bdgenomics/adam/api/java/JavaADAMContext.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/GenomicDataset.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/contig/NucleotideContigFragmentDataset.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/CoverageDataset.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/FeatureDataset.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/fragment/FragmentDataset.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordDataset.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/GenotypeDataset.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/VariantContextDataset.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/VariantDataset.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/feature/CoverageDatasetSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/feature/FeatureDatasetSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/fragment/FragmentDatasetSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordDatasetSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/variant/GenotypeDatasetSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/variant/VariantContextDatasetSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/variant/VariantDatasetSuite.scala

Fixes #1986.  Also adds java-specific methods where missing, most significantly `GenomicRDD.transformDataset(JFunction)`.

[ADAM-1986] Add java-specific methods where missing.

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/MarkDuplicates.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/MarkDuplicatesSuite.scala

Currently a supplemental read can be added to the sum of base qualities
of a duplicate candidate, artificially inflating its base quality sum
when mark duplicates is trying to choose the best read from the bunch.
This is one (the simplest and most superficial) fix to the problem. Just
filter supplemental reads out when summing.
Another solution could be to use the supplemental flag when setting the
"not primary read flag" in SAMRecordConverter.
Yet another would be to create a separate field in SingleReadBucket for
supplemental reads.
Not sure what the downstream effects of these different approaches are.

Filter supplemental reads from scoring

---

adam-python/version.py
adam-r/bdgenomics.adam/DESCRIPTION

See #2089, looks like the same might also be an issue for `adam-python/version.py`.
Should this be set to the current snapshot version `0.27.0-SNAPSHOT` on git head?

Update python and R versions.

---

adam-python/bdgenomics/adam/rdd.py

[ADAM-2127] Update python doc per GenomicRdd --> GenomicDataset change

---

adam-cli/src/main/scala/org/bdgenomics/adam/cli/TransformAlignments.scala
adam-core/pom.xml
adam-core/src/main/scala/org/bdgenomics/adam/models/ReferenceRegion.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/ADAMContextSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/contig/NucleotideContigFragmentDatasetSuite.scala
scripts/jenkins-test

As mentioned in #2108 , the available version of parquet-scala is stuck in 2.10. The cleanest way to get around this issue is probably to just remove this dependency.

Remove dependency on parquet-scala

---

pom.xml

Follow up to #2140.
The `parquet-scala` dependency can also be removed from `<dependencyManagement>`.

Remove parquet-scala dependency from dependencyManagement.

---

adam-core/src/main/scala/org/bdgenomics/adam/converters/AlignmentRecordConverter.scala
adam-core/src/main/scala/org/bdgenomics/adam/models/SAMFileHeaderWritable.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordDataset.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AnySAMInFormatter.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/BAMInFormatter.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/SAMInFormatter.scala
adam-core/src/main/scala/org/bdgenomics/adam/serialization/ADAMKryoRegistrator.scala
adam-core/src/test/scala/org/bdgenomics/adam/converters/AlignmentRecordConverterSuite.scala

[ADAM-1170] Deprecate SAMFileHeaderWritable

---

adam-cli/src/main/scala/org/bdgenomics/adam/cli/TransformFeatures.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/TransformGenotypes.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/TransformVariants.scala

[ADAM-2188] Add partition cli args to TransformVariants,Features.

---

README.md
scripts/jenkins-test

[ADAM-2194] Disable coveralls reporting from Jenkins test script

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala

[ADAM-2183] Drop default value for maximumLength

---

scripts/jenkins-test

Jenkins CI for #2203 was run against Spark 2.4.3, it is possible Spark 2.4.4 no longer requires Avro 1.8.x download step when installing for Scala 2.12.

Remove Avro 1.8.x download step from Jenkins Scala 2.12 installation.

---

pom.xml

These updates will allow bit-by-bit reproducible builds (in theory, at least).  We'll want to watch for https://issues.apache.org/jira/browse/MRELEASE-1029 to land.
See https://maven.apache.org/guides/mini/guide-reproducible-builds.html

Update maven plugin dependency versions.

---

adam-core/src/main/scala/org/bdgenomics/adam/converters/TranscriptEffectConverter.scala
adam-core/src/test/scala/org/bdgenomics/adam/converters/TranscriptEffectConverterSuite.scala

Fixes #2150 
From the VCF ANN specification:
> * cDNA_position ​/ (cDNA_len optional) : Position in cDNA and trancript’s cDNA length (one
based).
> * CDS_position ​/ (CDS_len optional)​: Position and number of coding bases (one based includes
START and STOP codons).
> * Protein_position ​/ (Protein_len optional)​: Position and number of AA (one based, including START, but not STOP).
Position should be a single value, but Ensembl VEP provides an interval (e.g. 7264-7275).

[ADAM-2150] Use interval start as position for Ensembl VEP ANN attributes

---

adam-core/src/main/scala/org/bdgenomics/adam/models/Attribute.scala
adam-core/src/main/scala/org/bdgenomics/adam/models/SequenceDictionary.scala

These changes significantly affect the performance of processing SAM/BAM files (x60 in my test cases).
The changes:
1. StringBuilder usage instead of many String.format, and using native Scala mkString.
2. While using the object SAMSequenceDictionary from the Samtools package, we pass a Scala implementation of an iterator, which, unfortunately, takes O(n) time to check its length.
Keep up the great work!

Performance improvements to SAM reading and processing

---

.github/workflows/deploy.yml

Occasionally the deploy Github action fails due to dependency download failures.

Add cache to deploy action
