bigdatagenomics/adam

adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala

Related to discussion in #553.

Makes maybeLoadVCF private.

---

adam-core/src/main/scala/org/bdgenomics/adam/util/ReferenceFile.scala

[ADAM-627] Makes ReferenceFile trait extend Serializable.

---

adam-core/src/test/scala/org/bdgenomics/adam/converters/SAMRecordConverterSuite.scala

- Added unit tests for mapped and unmapped SAMRecord to AlignmentRecord conversions.

[Adam] Tests for SAMRecordConverter.scala

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/BroadcastRegionJoin.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/ShuffleRegionJoin.scala

a few region-join nits

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDDFunctions.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variation/ADAMVCFOutputFormat.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variation/VariationRDDFunctions.scala

unify header-setting between BAM/SAM and VCF

---

adam-apis/src/main/scala/org/bdgenomics/adam/apis/java/JavaAlignmentRecordRDD.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/Flatten.scala
adam-cli/src/test/scala/org/bdgenomics/adam/cli/ParquetLister.scala
adam-core/pom.xml
adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMRDDFunctions.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/contig/NucleotideContigFragmentRDDFunctions.scala
adam-core/src/main/scala/org/bdgenomics/adam/util/ParquetFileTraversable.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/ADAMContextSuite.scala
pom.xml

Resolves #716. Depends on the 0.2.2 release of https://github.com/bigdatagenomics/utils, which I am releasing at this very moment.

[ADAM-716] Move to org.apache.parquet:1.7.0.

---

README.md

Clean up README links, other nits

---

adam-core/src/main/scala/org/bdgenomics/adam/models/SequenceDictionary.scala

stop writing contig names as md5 sums

---

adam-core/src/main/java/org/bdgenomics/adam/io/InterleavedFastqInputFormat.java
adam-core/src/main/java/org/bdgenomics/adam/io/SingleFastqInputFormat.java

[ADAM-812] fix for javadoc errors on JDK8, fixes #812

---

scripts/release/release.sh

[ADAM-868] make release branch and tag names consistent

---

adam-cli/src/main/scala/org/bdgenomics/adam/cli/ADAM2Fasta.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/Adam2Fastq.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/CountContigKmers.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/CountReadKmers.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/Vcf2ADAM.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/VcfAnnotation2ADAM.scala

Separate command line argument words by underscores

---

adam-cli/src/main/scala/org/bdgenomics/adam/cli/Transform.scala

[ADAM-920] Limit tag/orig qual flags in Transform.

---

pom.xml

[ADAM-960] Updating bdg-utils dependency version to 0.2.4

---

adam-cli/src/main/scala/org/bdgenomics/adam/cli/ADAM2Fastq.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/ADAMMain.scala

Moving Adam2Fastq to ADAM2Fastq

---

pom.xml

cf. https://github.com/hammerlab/guacamole/pull/444#issuecomment-214047984

bump commons-io version

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/variation/GenotypeRDD.scala

overlap query reflects new formats

---

adam-cli/pom.xml
adam-core/pom.xml
pom.xml

Remove code coverage profile

---

bin/adam-shell

[ADAM-1105] Use assembly jar in adam-shell.

---

pom.xml
scripts/jenkins-test

Resolves #1124. H/T @ryan-williams, "If I have seen further, it is by standing on the shoulders of giants.", etc, etc. ;)

[ADAM-1124] Add Scoverage and generate coverage reports in Jenkins.

---

adam-core/src/main/scala/org/bdgenomics/adam/converters/AlignmentRecordConverter.scala

[ADAM-1162] Write record group string name.

---

adam-cli/src/main/scala/org/bdgenomics/adam/cli/DictionaryCommand.scala
adam-core/src/main/scala/org/bdgenomics/adam/models/RecordGroupDictionary.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AnySAMOutFormatter.scala
adam-core/src/test/scala/org/bdgenomics/adam/converters/VariantContextConverterSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/models/SequenceDictionarySuite.scala

Small cleanup of "replacing uses of deprecated class SAMFileReader"

---

adam-cli/src/main/scala/org/bdgenomics/adam/cli/Reads2Coverage.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDD.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDDSuite.scala

Resolves #1227 and #1228. Testing now on high coverage WGS...

Fix reads2coverage issues

---

adam-core/src/main/scala/org/bdgenomics/adam/projections/FieldEnumeration.scala
adam-core/src/main/scala/org/bdgenomics/adam/projections/Projection.scala
adam-core/src/test/scala/org/bdgenomics/adam/projections/FieldEnumerationSuite.scala

Clean up documentation in `org.bdgenomics.adam.projection`.

---

pom.xml
scripts/move_to_spark_2.sh

[ADAM-1221] Bump Spark/Hadoop versions.

---

adam-apis/src/main/scala/org/bdgenomics/adam/apis/java/JavaADAMContext.scala
adam-apis/src/test/java/org/bdgenomics/adam/apis/java/JavaADAMFeatureConduit.java
adam-cli/src/main/scala/org/bdgenomics/adam/cli/Reads2Coverage.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/CoverageRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/FeatureParser.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/FeatureRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/Features.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDD.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/feature/CoverageRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/feature/FeatureRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDDSuite.scala

See https://github.com/bigdatagenomics/adam/issues/1083#issuecomment-233494794

Rename org.bdgenomics.adam.rdd.features package to o.b.a.rdd.feature

---

adam-core/src/main/scala/org/bdgenomics/adam/models/ReferenceRegion.scala
adam-core/src/test/scala/org/bdgenomics/adam/models/ReferenceRegionSuite.scala

[ADAM-1196] Add support for open ReferenceRegions.

---

src/test/resources/.gitignore

snuck in here https://github.com/bigdatagenomics/adam/commit/e8b0fcdd3feba937bb66cd72bbbdcad86039eeb1, woops

rm accidentally-added file

---

adam-apis/src/main/scala/org/bdgenomics/adam/apis/java/JavaADAMContext.scala
adam-apis/src/test/java/org/bdgenomics/adam/apis/java/JavaADAMAnnotationConduit.java
adam-apis/src/test/java/org/bdgenomics/adam/apis/java/JavaADAMGenotypeConduit.java
adam-apis/src/test/java/org/bdgenomics/adam/apis/java/JavaADAMVariantConduit.java
adam-cli/src/main/scala/org/bdgenomics/adam/cli/AlleleCount.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/VcfAnnotation2ADAM.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/ADAMVCFOutputFormat.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/GenotypeRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/VCFInFormatter.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/VCFOutFormatter.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/VariantAnnotationRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/VariantContextRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/VariantRDD.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/variant/VariantContextRDDSuite.scala

Rename org.bdgenomics.adam.rdd.variation package to o.b.a.rdd.variant

---

scripts/move_to_spark_1.sh

[ADAM-1307] Add script for moving to Spark 1.

---

scripts/move_to_spark_1.sh
scripts/move_to_spark_2.sh

[ADAM-1330] Move to Spark 2.1.0.

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/fragment/InterleavedFASTQInFormatter.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/BAMInFormatter.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/SAMInFormatter.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/VCFInFormatter.scala

Increase visibility for InFormatter case classes from package private to public

---

adam-core/src/main/scala/org/bdgenomics/adam/serialization/ADAMKryoRegistrator.scala

[ADAM-1367] Register Consensus array for serialization.

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/ADAMContextSuite.scala

[ADAM-1356] Make ADAMContext.getFsAndFiles and related protected visibility

---

pom.xml
scripts/jenkins-test

[ADAM-1403] Push coverage reports to Coveralls.

---

adam-core/src/main/scala/org/bdgenomics/adam/models/RecordGroupDictionary.scala
adam-core/src/test/scala/org/bdgenomics/adam/models/RecordGroupDictionarySuite.scala

[ADAM-1380] Adds isEmpty method to RecordGroupDictionary.

---

README.md
docs/source/02_installation.md

Minor doc updates per comment https://github.com/bigdatagenomics/adam/issues/1432#issuecomment-285584362

Update versions, etc. in build docs

---

docs/build.sh
scripts/publish-scaladoc.sh
scripts/release/release.sh

[ADAM-1453] Add hooks to publish ADAM docs from CI flow.

---

adam-cli/src/main/scala/org/bdgenomics/adam/cli/Transform.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDD.scala

[ADAM-1463] Rename recalibateBaseQualities method as recalibrateBaseQualities

---

README.md
adam-cli/src/main/scala/org/bdgenomics/adam/cli/ADAMMain.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/TransformAlignments.scala
adam-cli/src/test/scala/org/bdgenomics/adam/cli/ADAMMainSuite.scala
adam-cli/src/test/scala/org/bdgenomics/adam/cli/MergeShardsSuite.scala
adam-cli/src/test/scala/org/bdgenomics/adam/cli/Reads2FragmentsSuite.scala
adam-cli/src/test/scala/org/bdgenomics/adam/cli/TransformAlignmentsSuite.scala
adam-cli/src/test/scala/org/bdgenomics/adam/cli/ViewSuite.scala
docs/source/01_intro.md
docs/source/40_deploying_ADAM.md
docs/source/50_cli.md
scripts/jenkins-test

[ADAM-1328] Rename `Transform` to `TransformAlignments`.

---

adam-apis/src/main/scala/org/bdgenomics/adam/api/java/JavaADAMContext.scala
adam-apis/src/test/java/org/bdgenomics/adam/api/java/JavaADAMContigConduit.java
adam-apis/src/test/java/org/bdgenomics/adam/api/java/JavaADAMCoverageConduit.java
adam-apis/src/test/java/org/bdgenomics/adam/api/java/JavaADAMFeatureConduit.java
adam-apis/src/test/java/org/bdgenomics/adam/api/java/JavaADAMFragmentConduit.java
adam-apis/src/test/java/org/bdgenomics/adam/api/java/JavaADAMGenotypeConduit.java
adam-apis/src/test/java/org/bdgenomics/adam/api/java/JavaADAMReadConduit.java
adam-apis/src/test/java/org/bdgenomics/adam/api/java/JavaADAMVariantConduit.java
adam-apis/src/test/scala/org/bdgenomics/adam/api/java/JavaADAMContextSuite.scala

[ADAM-1537] Rename o.b.adam.apis.java package to o.b.adam.api.java

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/GenomicRDD.scala

[ADAM-1573] Remove unused Unaligned trait.

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/ManualRegionPartitioner.scala

[ADAM-1602] Add support for plain integer keys to ManualRegionPartitioner

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDD.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDDSuite.scala

[ADAM-1490] Add asSingleFile to saveAsFastq and related.

---

bin/pyadam

[ADAM-1647] Fix bad JAR discovery grep in bin/pyadam.

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/GenomicRDD.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDDSuite.scala

[ADAM-1679] Unmapped items should not get caught in requirement when sorting

---

adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala
adam-core/src/test/resources/invalid/truth_small_variants.vcf
adam-core/src/test/scala/org/bdgenomics/adam/rdd/variant/VariantContextRDDSuite.scala

[ADAM-1566] Merge VCF header lines with VCFHeaderLineCount.INTEGER correctly.

---

adam-core/src/main/scala/org/bdgenomics/adam/serialization/ADAMKryoRegistrator.scala
pom.xml
scripts/jenkins-test
scripts/move_to_spark_1.sh
scripts/move_to_spark_2.sh

[ADAM-1517] Bump Parquet version in a manner compatible with Spark 2.2.x

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/GenomicRDD.scala

Opening up permissions on GenericGenomicRDD

---

pom.xml
scripts/move_to_scala_2.10.sh

Tracking upcoming Hadoop-BAM version 7.8.1 release.

Update to hadoop-bam 7.9.0 and htsjdk 2.11.0.

---

adam-core/src/main/scala/org/bdgenomics/adam/models/ReferenceRegion.scala
adam-core/src/test/scala/org/bdgenomics/adam/models/ReferenceRegionSuite.scala

[ADAM-1747] Fixed subtract bug and tests

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/realignment/ModPartitioner.scala

[ADAM-1763] Apply absolute value to destination partition in ModPartitioner

---

docs/source/40_deploying_ADAM.md

[ADAM-1643] Add S3 access documentation.

---

CODE_OF_CONDUCT.md

[ADAM-1779] Adding code of contact adapted from the Contributor Convenant, version 1.4.

---

CONTRIBUTING.md
SUPPORT.md

[ADAM-1664] Add SUPPORT.md file to complement CONTRIBUTING.md.

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala

[ADAM-1784] loadIndexedBam should pass the raw globbed path to Hadoop-BAM

---

adam-distribution/src/main/assembly/assembly.xml
adam-python/Makefile
bin/adam-shell
bin/adam-submit
bin/adamR
bin/find-adam-assembly.sh
bin/find-adam-egg.sh
bin/find-script-dir.sh
bin/find-spark.sh
bin/pyadam
scripts/jenkins-test
scripts/jenkins-test-adam-shell.scala
scripts/jenkins-test-pyadam.py
scripts/release/release.sh

Resolves #1649. I took the liberty of rewriting the `bin` scripts to make them DRYer, and added tests that Jenkins will run for `adam-shell` and `pyadam`.

Add adamR script

---

adam-cli/src/main/scala/org/bdgenomics/adam/cli/MergeShards.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/GenomicRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/FeatureRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/VariantContextRDD.scala
adam-core/src/main/scala/org/bdgenomics/adam/util/FileMerger.scala
adam-core/src/main/scala/org/bdgenomics/adam/util/ManualRegionPartitioner.scala
adam-core/src/main/scala/org/bdgenomics/adam/util/ParallelFileMerger.scala
adam-core/src/main/scala/org/bdgenomics/adam/util/TextRddWriter.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/util/FileMergerSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/util/ParallelFileMergerSuite.scala

Fixes #1803 
More things needed to move than I would've preferred; I tried to keep visibility as narrow as possible.

[ADAM-1803] Refactor GenomicRDD.writeTextRdd to util.TextRddWriter.

---

docs/algorithms/bqsr.rst
docs/algorithms/dm.rst
docs/algorithms/reads.rst
docs/algorithms/ri.rst
docs/api/adamContext.rst
docs/api/genomicRdd.rst
docs/api/joins.rst
docs/api/overview.rst
docs/api/pipes.rst
docs/architecture/evidence.rst
docs/architecture/overview.rst
docs/architecture/schemas.rst
docs/architecture/stackModel.rst
docs/benchmarks/algorithms.rst
docs/cli/actions.rst
docs/cli/conversions.rst
docs/cli/overview.rst
docs/cli/printers.rst
docs/deploying/cgcloud.rst
docs/deploying/slurm.rst
docs/deploying/toil.rst
docs/deploying/yarn.rst
docs/downstream/cli.rst
docs/downstream/library.rst
docs/index.rst
docs/installation/example.rst
docs/installation/source.rst
docs/vendor/sphinxcontrib/__init__.py

[ADAM-1822] Misc docs cleanup

---

pom.xml

[ADAM-1817] Bump to Hadoop-BAM 7.9.1.

---

scripts/publish-scaladoc.sh

[ADAM-1843] Install sources before calling scala:doc in publish scaladoc

---

scripts/publish-scaladoc.sh

[ADAM-1845] Only build and publish scaladocs in publish-scaladoc.sh.

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/VCFOutFormatter.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/variant/VariantContextRDDSuite.scala

Required for https://github.com/bigdatagenomics/cannoli/issues/43.
Work in progress, currently Spark 2.x only due to `Accumulator` &rarr; `AccumulatorV2` deprecation.  I suggest waiting until post-0.23.0 when Spark 1.x support is dropped rather than trying to conditionally support both APIs.

Add optional accumulator for VCF header lines to VCFOutFormatter.

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala

[ADAM-1900] Close stream after reading VCF header.

---

pom.xml

[ADAM-1907] Bump to HTSJDK 2.13.2.

---

adam-core/src/main/scala/org/bdgenomics/adam/serialization/ADAMKryoRegistrator.scala

[ADAM-1925] Reduce logging level for ADAMKryoRegistrator.

---

adam-core/src/main/scala/org/bdgenomics/adam/util/FileExtensions.scala

[ADAM-1927] Increase visibility for util.FileExtensions for use downstream.

---

adam-core/src/main/scala/org/bdgenomics/adam/util/TwoBitFile.scala

This reverts commit 1eed8e8e464f8f92a6e87afc1d334e751423e810. Resolves #1923.

[ADAM-1923] Revert 1eed8e8

---

pom.xml

Resolves #1915. @heuermh @akmorrow13 need to do any validation on your side?

[ADAM-1915] Bump to Hadoop-BAM 7.9.2.

---

docs/conf.py

[ADAM-1917] Set minimal Sphinx version for Readthedocs build.

---

docs/requirements.txt

[ADAM-1917] Set Sphinx version in requirements.txt.

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/BEDOutFormatter.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/GFF3OutFormatter.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/GTFOutFormatter.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/VCFOutFormatter.scala

[ADAM-1949] Support validation stringency in out formatters.

---

adam-core/src/main/scala/org/bdgenomics/adam/util/FileMerger.scala

[ADAM-1984] Support file systems that don't set the scheme.

---

docs/api/joins.rst

[ADAM-1997] Nest list of region join types in joins doc.

---

adam-core/src/main/java/org/bdgenomics/adam/io/FastqRecordReader.java
adam-core/src/main/scala/org/bdgenomics/adam/converters/FastqRecordConverter.scala
adam-core/src/test/resources/fastq_nobases.fq
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDDSuite.scala

[ADAM-2006] Support loading 0-length reads as FASTQ.

---

docs/conf.py

Resolves #2020. Replaced references to other projects, while at it.

[ADAM-2020] Fix ReadTheDocs Github banner.

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/CoverageRDD.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/feature/CoverageRDDSuite.scala

[ADAM-2027] Add RDD and Dataset constructors to CoverageRDD.

---

adam-python/Makefile

Do not explicitly specify python version.

Update python MAKE file

---

adam-core/src/main/scala/org/bdgenomics/adam/converters/FastaConverter.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/FeatureParser.scala
adam-core/src/test/resources/ctg123.fasta.gff3
adam-core/src/test/scala/org/bdgenomics/adam/rdd/contig/NucleotideContigFragmentRDDSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/feature/FeatureRDDSuite.scala

Fixes #2037.
Ping @benwbooth for review.

[ADAM-2037] Support GFF3 files containing FASTA formatted sequences.

---

docs/installation/source.rst

[ADAM-2085] Update R installation docs re: libgit2 and SparkR.

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordDataset.scala
adam-python/bdgenomics/adam/rdd.py
adam-r/bdgenomics.adam/R/rdd.R

[ADAM-2013] Add java-friendly indel realignment method that accepts reference.

---

adam-core/src/main/scala/org/bdgenomics/adam/algorithms/consensus/ConsensusGenerator.scala
adam-python/bdgenomics/adam/rdd.py
adam-python/bdgenomics/adam/test/alignmentRecordDataset_test.py

[ADAM-2099] Add python realignIndelsFromKnownIndels method

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/realignment/RealignIndels.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/realignment/RealignmentTargetFinder.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/realignment/IndelRealignmentTargetSuite.scala

Have been digging into ADAM indel realignment and differences between it and the GATK implementation. While doing so I found that the targets from known sites are never explicitly taken into account as the targetsToAdd method on the ConsensusGenerator trait is never called. This change calls that method as part of the target generation process.

Add consensus targets to realignment targets

---

pom.xml

[ADAM-2120] Bump Spark dependency to version 2.3.3.

---

adam-cli/src/main/scala/org/bdgenomics/adam/cli/ADAM2Fasta.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/ADAM2Fastq.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/CountContigKmers.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/CountReadKmers.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/Fasta2ADAM.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/FileSystemUtils.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/PrintADAM.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/Reads2Coverage.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/TransformAlignments.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/TransformFeatures.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/TransformFragments.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/TransformGenotypes.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/TransformVariants.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/View.scala

[ADAM-2034] Check output path is writeable before running transformations

---

scripts/jenkins-test

[ADAM-2139] Update Spark version to 2.3.3 for Jenkins test

---

pom.xml

[ADAM-2147] Update maven-jar-plugin dependency version to 3.1.2.

---

adam-cli/src/main/scala/org/bdgenomics/adam/cli/FlagStat.scala
adam-python/Makefile
adam-python/bdgenomics/adam/test/__init__.py
pom.xml
scripts/jenkins-test

[ADAM-2145] Add Spark 2.4.3 and Scala 2.12 to Jenkins build

---

scripts/release/release.sh

[ADAM-2089] Bump Version in R DESCRIPTION file

---

scripts/release/release.sh

[ADAM-2153] Add Scala 2.12 artifacts to release script

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/fragment/FragmentDataset.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordDataset.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/GenotypeDataset.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/VariantContextDataset.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/VariantDataset.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/ADAMContextSuite.scala

[ADAM-2159] Add load methods for data frames

---

adam-cli/src/main/scala/org/bdgenomics/adam/cli/TransformFeatures.scala

[ADAM-2167] Add command line support for loading references in TransformFeatures

---

adam-cli/src/main/scala/org/bdgenomics/adam/cli/TransformFeatures.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/TransformSequences.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/TransformSlices.scala

[ADAM-2168]  Add command line option re: creating references from FASTA sources

---

adam-cli/src/main/scala/org/bdgenomics/adam/cli/ADAMMain.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/Coverage.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/TransformAlignments.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/TransformFragments.scala
adam-cli/src/test/scala/org/bdgenomics/adam/cli/CoverageSuite.scala
adam-cli/src/test/scala/org/bdgenomics/adam/cli/MergeShardsSuite.scala
adam-cli/src/test/scala/org/bdgenomics/adam/cli/TransformAlignmentsSuite.scala
adam-cli/src/test/scala/org/bdgenomics/adam/cli/TransformFragmentsSuite.scala
adam-core/src/main/scala/org/bdgenomics/adam/instrumentation/Timers.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/fragment/FragmentDataset.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordDataset.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/ADAMContextSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/fragment/FragmentDatasetSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordDatasetSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/MarkDuplicatesSuite.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/read/realignment/RealignIndelsSuite.scala
adam-python/bdgenomics/adam/rdd.py
adam-python/bdgenomics/adam/test/alignmentRecordDataset_test.py
adam-r/bdgenomics.adam/R/generics.R
adam-r/bdgenomics.adam/R/rdd.R
adam-r/bdgenomics.adam/tests/testthat/test_alignmentRecordDataset.R
docs/cli/actions.rst
docs/cli/conversions.rst
scripts/jenkins-test

[ADAM-2172] Rename reads to alignments in methods where appropriate

---

pom.xml

[ADAM-2177] Bump bdg-formats dependency version to 0.13.0

---

pom.xml
scripts/jenkins-test

[ADAM-2202] Bump Apache Spark dependency version to 2.4.4.

---

adam-core/src/main/scala/org/bdgenomics/adam/instrumentation/Timers.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordDataset.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/VariantContextDataset.scala

[ADAM-2189] Add htsjdk conversion methods to VariantContextDataset

---

pom.xml

[ADAM-2208] Bump bdg-formats dependency version to 0.14.0

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/GenotypeDataset.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/VariantContextDataset.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/VariantDataset.scala

[ADAM-2215] Add Avro-friendly ctrs to rdd.variant package

---

adam-core/src/main/scala/org/bdgenomics/adam/util/ADAMShell.scala

[ADAM-2218] Add default Set.empty to printAttributes key method parameter.

---

adam-core/src/main/scala/org/bdgenomics/adam/util/ADAMShell.scala

[ADAM-2219] Add printAttributes methods for Reads, Sequences, Slices

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/GenomicDataset.scala

[ADAM-2224] Use compressionCodec for named parameter.

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/GenomicDataset.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/CoverageDataset.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/FeatureDataset.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/fragment/FragmentDataset.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AlignmentDataset.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/ReadDataset.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/sequence/SequenceDataset.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/sequence/SliceDataset.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/GenotypeDataset.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/VariantContextDataset.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/VariantDataset.scala

[ADAM-2224] Complete refactoring of compressionCodec for named parameter.

---

pom.xml

[ADAM-2233] Update bdg-formats dependency version to 0.15.0.

---

scripts/release/release.sh

[ADAM-2235] Update github-changes-maven-plugin dependency version to 1.1

---

README.md

[ADAM-2228] Remove Jenkins build status badge

---

adam-cli/src/test/scala/org/bdgenomics/adam/cli/AboutSuite.scala

[ADAM-2241] Commit template substitution may not be available if building from tarball

---

pom.xml

[ADAM-2248] Bump Apache Spark dependency version to 2.4.5

---

pom.xml

[ADAM-2252] Update bdg-utils dependency version to 0.2.16

---

adam-core/src/main/scala/org/bdgenomics/adam/instrumentation/Timers.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/GenomicDataset.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/ADAMBAMOutputFormat.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/ADAMCRAMOutputFormat.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/ADAMSAMOutputFormat.scala
adam-core/src/main/scala/org/bdgenomics/adam/util/ADAMShell.scala
docs/cli/actions.rst
docs/cli/conversions.rst
docs/cli/overview.rst
docs/cli/printers.rst

[ADAM-2254] Add deprecated annotations for code to be removed to support Spark 3

---

pom.xml

[ADAM-2259] Bump slf4j dependency version to 1.7.30.

---

pom.xml
scripts/jenkins-test
scripts/move_to_spark_2.sh

[ADAM-2262] Update Spark dependency version to 2.4.6

---

adam-python/setup.py
scripts/jenkins-test

[ADAM-2221] Remove support for Python 2.7

---

adam-cli/src/main/scala/org/bdgenomics/adam/cli/ADAMMain.scala

[ADAM-2270] Add cite DOI link to command line --version output

---

pom.xml
scripts/jenkins-test
scripts/move_to_spark_2.sh
scripts/move_to_spark_3.sh

Update Spark dependency version to 3.0.1

---

README.md
docs/installation/source.rst
pom.xml
scripts/jenkins-test
scripts/move_to_scala_2.11.sh
scripts/move_to_scala_2.12.sh
scripts/release/release.sh

Fixes #2283, fixes #2284, fixes #2285, fixes #2287

Update build and release matrix

---

CHANGES.md

[ADAM-2290] Remove duplicate version 0.33.0 release notes in changelog

---

adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/FeatureDataset.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AlignmentDataset.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/GenotypeDataset.scala
adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/VariantDataset.scala
adam-core/src/test/scala/org/bdgenomics/adam/rdd/feature/FeatureDatasetSuite.scala

[ADAM-1877] Add convenience method to filter to reference name

---

adam-cli/src/main/scala/org/bdgenomics/adam/cli/ADAM2Fastq.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/CountReadKmers.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/Coverage.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/CramArgs.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/FlagStat.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/TransformAlignments.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/TransformFragments.scala
adam-cli/src/main/scala/org/bdgenomics/adam/cli/View.scala

[ADAM-2293] Add CRAM reference argument to CLI for loading alignments and fragments

---

pom.xml
scripts/jenkins-test
scripts/move_to_spark_3.sh

[ADAM-2300] Update Spark dependency version to 3.0.2

---

pom.xml
scripts/move_to_spark_2.sh
scripts/move_to_spark_3.sh

[ADAM-2302] Update Spark dependency version to 3.1.1

---

pom.xml
scripts/move_to_spark_2.sh
scripts/move_to_spark_3.sh

[ADAM-2317] Update Spark dependency version to 3.1.2

---

.github/workflows/ci.yml
.github/workflows/deploy.yml

Migrate Github Actions JDK from 'adopt' to 'temurin'

---

adam-core/src/main/scala/org/bdgenomics/adam/serialization/ADAMKryoRegistrator.scala

[ADAM-2185] Reduce classForName calls to improve registrator performance

---

README.md
docs/installation/source.rst

Add conda, homebrew, biocontainers installation docs

---

pom.xml

Update spark dependency version to 3.2.1

---

adam-core/src/main/scala/org/bdgenomics/adam/util/ADAMShell.scala

Feature strand may be null

---

adam-core/src/main/scala/org/bdgenomics/adam/ds/sequence/SliceDataset.scala

[ADAM-2362] Account for duplicate kmers on left flank

---

adam-core/src/main/scala/org/bdgenomics/adam/util/FileExtensions.scala
adam-core/src/test/scala/org/bdgenomics/adam/util/FileExtensionsSuite.scala

[ADAM-2295] Add workaround for BAM files hosted on SRA s3 archive

---

pom.xml

Update bdg-utils dependency version to 1.0

---

pom.xml

Update bdg-formats dependency version to 1.0

---

pom.xml

Update avro dependency version to 1.11.1

---

pom.xml

Update Spark dependency version to 3.3.2

---

CHANGES.md

Remove duplicate release version 1.0.1 section from CHANGES.md

---

pom.xml

Update Spark dependency version to 3.5.2

---

pom.xml

Update Apache Spark dependency version to 3.5.5
